### ISSUE TITLE
Tulsi generated  failed

### ISSUE THREAD

**Issue by bushixingan** [bazelbuild/tulsi#101]
hello,
When I use tulsi to generate a Xcode project ,an error occurred
he told me,
ERROR: An error occurred during the fetch of repository 'local_config_git':
ERROR: /private/var/tmp/_bazel_shenming/0f5d0daefd6f87499857aa68c4ad73ed/external/org_tensorflow/tensorflow/core/BUILD:2785:1: @org_tensorflow//tensorflow/core:version_info_gen depends on @local_config_git//:gen/spec.json in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Traceback (most recent call last):
ERROR: /private/var/tmp/_bazel_shenming/0f5d0daefd6f87499857aa68c4ad73ed/external/org_tensorflow/tensorflow/core/BUILD:2785:1: @org_tensorflow//tensorflow/core:version_info_gen depends on @local_config_git//:gen/head in repository @local_config_git which failed to fetch. no such package '@local_config_git//': Traceback (most recent call last):
...
General failure: Bazel aspects could not be built.

Could u tell me how to solve this about 'local_config_git'?
I couldn't find it anywhere

**Comment by sergiocampama** [comment]
That looks like an issue with how tensorflow is configured, and not something Tulsi related. Could you file this issue at the Tensorflow project instead?
