### ISSUE TITLE
External projects don't resolve sources properly

### ISSUE THREAD

**Issue by thii** [bazelbuild/tulsi#109]
External project sources get set to the path `tulsi-workspace/external/MyExternalWorkspace` while `tulsi-workspace` doesn't exist (it doesn't get generated anymore as of the version 0.4.276307939.20191023 (the latest when I'm writing this).

```
94C190809CD0FD5100000000 /* @Reachability */ = {
  isa = PBXGroup;
  children = (
    00C7263701CA77DC00000002 /* BUILD.bazel */,
    00C726379A5E4D8600000000 /* Reachability.h */,
    00C7263733DBC80E00000000 /* Reachability.m */,
  );
  name = "@Reachability";
  path = "tulsi-workspace/external/Reachability";
  sourceTree = "<group>";
};
```

**Comment by DavidGoldman** [comment]
I would expect it to exist after Bazel creates symlinks (e.g. after building), where do you see the `MyExternalWorkspace` in the Bazel execution root?

**Comment by thii** [comment]
There is a `tulsi-workspace` symlink at `MyProject.xcodeproj/.tulsi/tulsi-workspace` but not at the project root. `MyExternalWorkspace` is at `MyProject.xcodeproj/.tulsi/tulsi-workspace/external/MyExternalWorkspace`.

The current workaround is to manually create a symlink `tulsi-workspace -> MyProject.xcodeproj/.tulsi/tulsi-workspace`.

**Comment by DavidGoldman** [comment]
This is likely an oversight in 7d7323065838d7d5f0ea756517ebfb21aa502a9c, we should make sure all references to the `tulsi-workspace` are via the proper symlink in the xcodeproj.

**Comment by cpsauer** [comment]
Ran into this, too, and can confirm that linking does indeed still work as a workaround. That is, for anyone else seeing red (broken) links to external files, running `ln -s <MY_PROJECT>.xcodeproj/.tulsi/tulsi-workspace .` from the workspace route fixes things.

Any word or plan on a more complete fix?
