### ISSUE TITLE
xcode11 build failed,  other version Xcode(10.3)  build did not complete

### ISSUE THREAD

**Issue by Qiyun2014** [bazelbuild/tulsi#110]
![image](https://user-images.githubusercontent.com/7145066/67915958-4111d300-fbcf-11e9-9221-a691faa41cc0.png)

**Comment by Qiyun2014** [comment]
![WX20191031-111545](https://user-images.githubusercontent.com/7145066/67916165-cdbc9100-fbcf-11e9-94ed-bdca00acfba7.png)

**Comment by MHX792** [comment]
Same problem. Could you fix it @Qiyun2014 ?

**Comment by keith** [comment]
If you're still seeing issues with this with a newer version of bazel + tulsi + xcode please open a new issue
