### ISSUE TITLE
Debugger doesn't seem to attach during unit tests

### ISSUE THREAD

**Issue by bkase** [bazelbuild/tulsi#12]
Hi! Whenever I'm running a test target generated by Tulsi (from an ios_test rule), any breakpoints set in Xcode are never hit.

Even if I construct a test that sleeps for a few seconds, so I'm able to press the "pause" button on the debug pane, the test does not break when clicking on that button.

```objective-c
#import <XCTest/XCTest.h>

@interface SlowTests : XCTestCase

@end

@implementation SlowTests

- (void)testSlow
{
    sleep(4);
    XCTFail(@"Breakpoints don't work");
}

@end
```

Do you have any idea what might cause this behavior, and how we can fix it?

**Comment by dmishe** [comment]
Is there anything in the Xcode Debug console that would provide a clue?

**Comment by bkase** [comment]
Hmm, I'm glad you asked that because the pause button seems to be working today! Perhaps Xcode just needed to restart.

I'll close this for now, and re-open if I figure out how to reliably reproduce this. Thanks!
