### ISSUE TITLE
Detecting Xcode 11.3.1 is broken when using generated Tulsi project in a workspace

### ISSUE THREAD

**Issue by kjteske** [bazelbuild/tulsi#124]
In `bazel_build.py`, `_GetXcodeVersionString()` has a regex to get the Xcode version from `XCODE_VERSION_ACTUAL` environment variable that Xcode sets. When building from the Tulsi-generated project itself, this is correctly set to 1131, but when I drag the Tulsi-genenerated project into our larger workspace, Xcode sets XCODE_VERSION_ACTUAL incorrectly to 1130. This seems like an Apple bug, I filed Feedback Assistant 7545201 to them.

This leads to a Tulsi error that it can't find the version of Xcode:

```
ERROR: /private/var/tmp/_bazel_kyle/ae06442f5194347a35d4d20a121afb9e/external/local_config_xcode/BUILD:30:1: in xcode_config rule @local_config_xcode//:host_xcodes: --xcode_version=11.3.0.11C504 specified, but '11.3.0.11C504' is not an available Xcode version. available versions: [10.1.0.10B61, 11.3.1.11C504, 11.2.1.11B500]. If you believe you have '11.3.0.11C504' installed, try running "bazel shutdown", and then re-run your command.
```

I don't see any Xcode environment variables in this case that set the correct version:
```
    export XCODE_PRODUCT_BUILD_VERSION=11C504
    export XCODE_VERSION_ACTUAL=1130
    export XCODE_VERSION_MAJOR=1100
    export XCODE_VERSION_MINOR=1130

```

But perhaps as a workaround within Tulsi itself, Tulsi could look up Xcode version from `<...>/Xcode.app/Contents/version.plist`, there are plenty of environment variables with the path to `Xcode.app`. Here's `version.plist`:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildAliasOf</key>
	<string>IDEFrameworks</string>
	<key>BuildVersion</key>
	<string>2</string>
	<key>CFBundleShortVersionString</key>
	<string>11.3.1</string>
	<key>CFBundleVersion</key>
	<string>15715</string>
	<key>ProductBuildVersion</key>
	<string>11C504</string>
	<key>ProjectName</key>
	<string>IDEFrameworks</string>
	<key>SourceVersion</key>
	<string>15715000000000000</string>
</dict>
</plist>

```

**Comment by DavidGoldman** [comment]
Are you sure about this? See also https://github.com/bazelbuild/tulsi/pull/113, I think for some reason you might have an odd Xcode installation (e.g. it somehow became corrupt w.r.t to version). I will try to check this locally.

**Comment by DavidGoldman** [comment]
Confirmed that locally I see:

```
    export XCODE_PRODUCT_BUILD_VERSION=11C505
    export XCODE_VERSION_ACTUAL=1131
    export XCODE_VERSION_MAJOR=1100
    export XCODE_VERSION_MINOR=1130
```

This is likely an issue with your installation or perhaps an older invalid Xcode?

**Comment by DavidGoldman** [comment]
Feel free to re-open if you're unable to confirm the issue.

**Comment by kjteske** [comment]
Thanks for taking the time to check it out.

I just downloaded a fresh Xcode 11.3.1 from developer.apple.com (instead of App Store Xcode), deleted DerivedData, and rebooted my computer. I still get the same behavior. I'm stumped. Nothing in our workspace files seems suspicious.

For now, it's easy enough to workaround (hand-modify bazel_build.py) and we're only experimenting/evaluating Bazel & Tulsi, so we're not really depending on this in production. If we start hitting this more often, I'll re-open this issue and can contribute a PR.

**Comment by kjteske** [comment]
No direct replies to my Apple feedback report, but it has been marked with a Resolution: "Potential fix identified - For a future OS update".
I'm on Catalina 10.15.2.

**Comment by thii** [comment]
Confirmed this is reproducible. The condition is to use the generated project **in a workspace**. Building with the `.xcodeproj` alone works fine.

**Comment by kjteske** [comment]
Yes, I've reproduced this on a new laptop, and several co-workers have hit it too. Will post a PR shortly.

**Comment by kjteske** [comment]
@DavidGoldman  - I don't seem to have permissions to re-open this issue.

I posted a fix for review to gerrit at https://bazel-review.googlesource.com/c/tulsi/+/132211.

This is my first time using gerrit, let me know if I'm not following the process correctly.
