### ISSUE TITLE
Tulsi-generated app won't run; claims Mac OS version is too old, despite setting deployment target

### ISSUE THREAD

**Issue by dwebb23** [bazelbuild/tulsi#127]
Using Tulsi to build the Xcode project for the very simple bazel project attached to this issue, when I build & run the app in Xcode, it fails with this error message:

"Dan’s MacBook Pro runs macOS 10.14.6, which is lower than bzl’s minimum deployment target. Change your project’s minimum deployment target or upgrade Dan’s MacBook Pro’s version of macOS."

I changed the MacOS development target to 10.14 (in project->Info->Deployment Target), and it still won't run.  I cleaned and built from scratch, still no luck.  I opened the project.pbxproj in TextEdit and verified that the version is 10.14 everywhere in the project.

The contents of the .app look weirdly incomplete, and maybe that's what is causing the (erroneous) error message.  But I can't figure out what's wrong.

Versions of everything I'm using:
 - OS X 10.14.6
 - Xcode 11.1 (which contains the 10.15 SDK)
 - Tulsi 0.20200115.88 (cloned on 2/4/20)
 - Bazel: 2.0.0-homebrew

[bzl.zip](https://github.com/bazelbuild/tulsi/files/4168120/bzl.zip)

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
