### ISSUE TITLE
Tulsi build failing

### ISSUE THREAD

**Issue by lpollard11** [bazelbuild/tulsi#13]
I am trying to build a simple Xcode project using Tulsi, but the Tulsi build keeps failing in Xcode anytime I try to run the project. The error is "Bazel build failed". I followed all the instructions and purposely made the Xcode project very simple yet it still still fails. I attached a screen shot of my file structure, the WORKSPACE file, and the BUILD file. The Bazel executable I'm using is what I downloaded from https://bazel.build/versions/master/docs/install-compile-source.html. 

Please let me know if I can provide any more info to see why it keep failing.

Thank you.

<img width="614" alt="screen shot 2017-04-19 at 5 32 43 pm" src="https://cloud.githubusercontent.com/assets/8551495/25203177/3ce83a8a-2526-11e7-92b3-f9ad38ecc733.png">

[WORKSPACE.TXT](https://github.com/bazelbuild/tulsi/files/938558/WORKSPACE.TXT)
[BUILD.TXT](https://github.com/bazelbuild/tulsi/files/938559/BUILD.TXT)

**Comment by StevenEWright** [comment]
Couple things...

1.) it would be helpful if you include the full error (which you can get my looking at the Xcode build log).

2.) You have at least one minor issue with your BUILD file. You shouldn't include your headers in the srcs list. Rather, hdrs.

3.) Tulsi has a known issue with the current version of Xcode. See: https://github.com/bazelbuild/tulsi/issues/3 

I'd recommend building with regular Bazel for now - or at least getting a regular Bazel build working first, and then trying to get Tulsi to work.

You're not far off. You're just running into a few "first timer" problems, and you'll probably be inconvenienced by some Tulsi issues since it's so new.

I'd suggest the moderators close this issue unless/until the OP includes details on a new unknown issue.

**Comment by lpollard11** [comment]
Thanks for your response Steven! I've attached the build logs. Please let me know if there's anything I can do differently on my end to avoid this issue.

I just had a few quick questions:
1) Can I get an Xcode project generated by building with regular Bazel? I'd like to be able to use Bazel to build Xcode projects quicker. I read here [Migrating from the native rules](https://github.com/bazelbuild/rules_apple/wiki/Migrating-from-the-native-rules) that Bazel no longer generates Xcode projects.

2. Can I use Tulsi with an Xcode project that is purely in Swift?

Thanks again for your help! Tulsi seems incredibly useful so I definitely want to get this working ev eventually.

<img width="758" alt="screen shot 2017-04-20 at 11 28 39 am" src="https://cloud.githubusercontent.com/assets/8551495/25238903/9711596a-25bc-11e7-9ba1-574a9720d7fa.png">

**Comment by StevenEWright** [comment]
Great! Stoked I could help! 

Yes, so the error you're getting is definitely the same as described in the other issue (which also provides a work around if you're willing to jump through those hoops - and that should work for you at this point).

To answer your other questions:

1.) Yes, It still can, for now. The docs for Tulsi jumped the gun a bit in that regard. But you'll need to migrate soon - so... your call.

2.) I'll let someone else field this question. There has been a lot of churn lately surrounding building swift libs, and I've been waiting myself till it stabilizes a bit before I messed with it.

**Comment by dmishe** [comment]
To answer 1 and 2. You should be using Tulsi instead of generating Xcode projects from bazel (this is deprecated) and that will let you use Swift.

The error makes it look like bazel is picking up tvos cpu, for an iOS build, which is wrong. @c-parsons, do you know what can cause this?

**Comment by StevenEWright** [comment]
@dmishe See: https://github.com/bazelbuild/tulsi/issues/3

**Comment by c-parsons** [comment]
Actually, the error is indicating that likely there is a toolchain defined in a BUILD file for tvos, but that it's not available in the CROSSTOOL definition.

That's quite unusual for Bazel out-of-the-box. Have you locally modified anything under tools/ ?

Can you paste the contents of the file located at $(bazel info execution_root)/external/local_config_cc/BUILD ?

**Comment by lpollard11** [comment]
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "malloc",
)

cc_library(
    name = "stl",
)

filegroup(
    name = "empty",
    srcs = [],
)

filegroup(
    name = "cc_wrapper",
    srcs = ["cc_wrapper.sh"],
)

# This is the entry point for --crosstool_top.  Toolchains are found
# by lopping off the name of --crosstool_top and searching for
# the "${CPU}" entry in the toolchains attribute.
cc_toolchain_suite(
    name = "toolchain",
    toolchains = {
        "darwin|compiler": ":cc-compiler-darwin",
        "armeabi-v7a|compiler": ":cc-compiler-armeabi-v7a",
        "ios_x86_64|compiler": ":cc-compiler-ios_x86_64",
    },
)

cc_toolchain(
    name = "cc-compiler-darwin",
    all_files = ":cc_wrapper",
    compiler_files = ":cc_wrapper",
    cpu = "local",
    dwp_files = ":empty",
    dynamic_runtime_libs = [":empty"],
    linker_files = ":cc_wrapper",
    objcopy_files = ":empty",
    static_runtime_libs = [":empty"],
    strip_files = ":empty",
    supports_param_files = 0,
)


# Android tooling requires a default toolchain for the armeabi-v7a cpu.
cc_toolchain(
    name = "cc-compiler-armeabi-v7a",
    all_files = ":empty",
    compiler_files = ":empty",
    cpu = "local",
    dwp_files = ":empty",
    dynamic_runtime_libs = [":empty"],
    linker_files = ":empty",
    objcopy_files = ":empty",
    static_runtime_libs = [":empty"],
    strip_files = ":empty",
    supports_param_files = 1,
)

# ios crosstool configuration requires a default toolchain for the
# ios_x86_64 cpu.
cc_toolchain(
    name = "cc-compiler-ios_x86_64",
    all_files = ":empty",
    compiler_files = ":empty",
    cpu = "local",
    dwp_files = ":empty",
    dynamic_runtime_libs = [":empty"],
    linker_files = ":empty",
    objcopy_files = ":empty",
    static_runtime_libs = [":empty"],
    strip_files = ":empty",
    supports_param_files = 1,
)

**Comment by lpollard11** [comment]
It looks like this fix _ solved the build issue for an Objective-C project. But I am now trying Tulsi with a simple Swift project and I'm getting the attached error. It looks like "object of type 'apple_common' has no field 'AppleDebugOutputs'." is the error. 

I attached a screenshot of the error and my current BUILD file. and WORKSPACE file.

Thanks again for your help!
<img width="1015" alt="screen shot 2017-04-28 at 2 53 15 pm" src="https://cloud.githubusercontent.com/assets/8551495/25542995/d67537c2-2c22-11e7-8769-93ffd9287247.png">
[WORKSPACE.TXT](https://github.com/bazelbuild/tulsi/files/965286/WORKSPACE.TXT)
[BUILD.TXT](https://github.com/bazelbuild/tulsi/files/965287/BUILD.TXT)

**Comment by dmishe** [comment]
Unfortunatelly you hit a case where the bazel release is a bit behind apple rules. That property was added in https://github.com/bazelbuild/bazel/commit/48e1d5b86c5c32e8b9023518254ac9023c26082f#diff-0e81dcb8e4effd4ee5528770c4cf625aR146 which  is newer than 0.4.5 release.

You will have to build bazel at HEAD to use these new rules. See more at https://github.com/bazelbuild/rules_apple#apple-rules-for-bazel

**Comment by lpollard11** [comment]
I cloned bazel at HEAD and tried to run "bash ./compile.sh" in order to generate the bazel binary as indicated here https://bazel.build/versions/master/docs/install-compile-source.html. However, I get this error "ERROR: Must specify PROTOC if not bootstrapping from the distribution artifact".

It seems like I'm supposed to be able to do this according to https://github.com/bazelbuild/bazel/issues/2140

Please advise on the proper way to clone and get the proper bazel binary for me to use with Tulsi to generate the correct Xcode project. Thanks!

**Comment by dmishe** [comment]
@damienmg would you please route this issue to the proper bazel issue?

**Comment by lpollard11** [comment]
@damienmg Please let me know where you route this issue to so that I can follow along and get Tusli working for Swift projects. Thanks!

**Comment by damienmg** [comment]
You are supposed to build bazel with bazel or use the distribution artifact. The easiest way is probably the former. There is no bazel issue there.

**Comment by lpollard11** [comment]
@damienmg I am using bazel to build bazel, but as indicated above, in order for me to me able to use the rules in [here](https://github.com/bazelbuild/rules_apple) I need to build bazel from HEAD. 

Therefore, I cannot use the bazel binary from [releases](https://github.com/bazelbuild/bazel/releases). I need to clone from HEAD and then run "bash ./compile.sh" to create the bazel binary. However, when I do that, I get this error "ERROR: Must specify PROTOC if not bootstrapping from the distribution artifact". I looked it up and it appears there's no work around [here](https://github.com/bazelbuild/bazel/issues/2140).

It would be great if you could indicate how I can create the bazel binary from HEAD without running into the above error.

**Comment by damienmg** [comment]
You need to do `bazel build src:bazel`

**Comment by lpollard11** [comment]
@damienmg That worked! Thanks for your help. I needed to use the bazel binary that was generated in bazel/bazel-bin/src/.

**Comment by dmishe** [comment]
It looks like the issue here is resolved? Closing, feel free to update.
