### ISSUE TITLE
sh build_and_run.sh --version_failures

### ISSUE THREAD

**Issue by chenzhibo** [bazelbuild/tulsi#131]
ERROR: /Users/chenzhibo/tulsi/tulsi/BUILD:62:1: Linking of rule '//:tulsi.__internal__.apple_binary' failed (Exit 1) wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -ObjC -arch x86_64 -filelist ... (remaining 26 argument(s) skipped)

**Comment by keith** [comment]
This isn't enough info to understand what's going on here, if you're still seeing this with a newer version of bazel + HEAD of tulsi please open a new issue!
