### ISSUE TITLE
Arguments passed to clang via swiftc aren't parsed properly

### ISSUE THREAD

**Issue by thii** [bazelbuild/tulsi#134]
Example: 

Given `swift_copts = ["-Xcc", "-IDir1", "-Xcc", "-IDir2"]`, `Dir1` and `Dir2` are added to the Swift Import Paths, but those `-Xcc`s are left over and are added to Other Swift Flags as `-Xcc -Xcc`.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
