### ISSUE TITLE
Certain warnings being shown as errors in Xcode build log

### ISSUE THREAD

**Issue by thii** [bazelbuild/tulsi#135]
Certain warnings (like module cache not found warnings) were being shown like errors in Xcode. They don't fail the build, though (because they're not errors), but Xcode shows them in red and at the end of the build it shows this additional warning:

```
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure
```

<img width="879" alt="Screen Shot 2020-03-25 at 18 38 22" src="https://user-images.githubusercontent.com/4506500/77523297-e30cc180-6ec8-11ea-9e4d-167e3a8d69d3.png">

And it seems like only certain patterns of warnings being treated like this. The following example reproduces the issue (try building an app which takes `dummy.txt` as a resource):

```
genrule(
    name = "dummy",
    outs = ["dummy.txt"],
    cmd = """
        echo warning: No such file or directory
        touch $@
    """,
)
```

**Comment by thii** [comment]
If it's easier, building the Tulsi app with this change to `//:combine_strings` also reproduces the issue. Oddly enough, the warning has to be exactly `No such file or directory`.

```diff
diff --git a/BUILD b/BUILD
index 9963588..ab898d4 100644
--- a/BUILD
+++ b/BUILD
@@ -44,6 +44,7 @@ genrule(
         "en.lproj/Localizable.strings",
     ],
     cmd = (
+        "echo warning: No such file or directory;" +
         "cat $(location //src/Tulsi:en.lproj/Localizable.strings) > $(location en.lproj/Localizable.strings); " +
         "echo '\n\n' >> $(location en.lproj/Localizable.strings); " +
         "cat $(location //src/TulsiGenerator:en.lproj/Localizable.strings) >> $(location en.lproj/Localizable.strings); "
```

**Comment by thii** [comment]
Looks like it's an Xcode issue rather than a Tulsi issue. I guess the following regex should catch these kind of warnings too.
https://github.com/bazelbuild/tulsi/blob/c245681d4fa860ba75e57ec73bf03603fdc2eca7/src/TulsiGenerator/Scripts/bazel_build.py#L688-L692

**Comment by keith** [comment]
You're seeing this from the dSYM generation right? If so for reference: https://forums.swift.org/t/swift-behavior-of-gmodules-and-dsyms/23211

**Comment by keith** [comment]
I've actually thought in the past that we should try to filter this in bazel itself

**Comment by thii** [comment]
Indeed. Disabling dSYM generation and they went away. Thanks for the the reference. Is the recommended way now is to pass `-Xfrontend -no-clang-module-breadcrumbs`?

**Comment by thii** [comment]
Oh, but this flag didn't seem to suppress the warnings about system modules.

**Comment by keith** [comment]
We haven't done anything about this, I've been meaning to get back to it since AFAICT it's not a "real" problem, so potentially we could add a flag to dsymutil to opt out of these

**Comment by zh-se** [comment]
Hi there! I have the same issue and it's not related to dSYM generation issue.
Just all bazel warnings are marked as errors in xCode. For example:
![image](https://user-images.githubusercontent.com/3619474/78793144-a8bc1d80-79ba-11ea-9196-f719e0ebcbdb.png)

bazel build from terminal:
<img width="898" alt="image" src="https://user-images.githubusercontent.com/3619474/78793531-33048180-79bb-11ea-8ca0-743a72dcca02.png">

**Comment by keith** [comment]
@zh-se that looks like a separate issue, potentially because of the colors being in the output Xcode may not be parsing `warning:` correctly, if you're still seeing this can you create a separate issue?

**Comment by zh-se** [comment]
@keith thanks for the help. You're right! The reason is that I added a flag to .bazelrc file for colorizing output.
