### ISSUE TITLE
Tulsi actually does a full build when generating the Xcode project

### ISSUE THREAD

**Issue by thii** [bazelbuild/tulsi#137]
Tulsi actually does a full build when generating the Xcode project, when it is extracting info for rules. I'm still investigating the reproducible condition and will provide a minimal example if possible.

**Comment by DavidGoldman** [comment]
It shouldn't do a full build due to the output groups, although I believe we do need to build some things (infoplists for extension IIRC). Are you sure it's doing a full build and not a very limited build?

**Comment by thii** [comment]
In my tests it took almost the same as a full build. When building from a clean state without cache, a full build took 890s while an Xcode project generation took 800s. There were swift and clang processes running the compiling commands in the background.

**Comment by thii** [comment]
What made me believe that it was doing a full build is that the first build after opening the generated project finished very fast—from the build log it only did the "Bundling, processing and signing" action.

**Comment by thii** [comment]
> It shouldn't do a full build due to the output groups

Thanks for this—it was because I had `dsyms` to the output groups.

**Comment by thii** [comment]
What do you think about adding `-dsyms` to the Tulsi's default generation command's output groups?

**Comment by DavidGoldman** [comment]
Tulsi adds the `--apple_generate_dsym` flag for release builds by default, you could add that yourself for debug builds. Why do you want to enable dSYMs by default?

**Comment by thii** [comment]
We have some configurations that only build for release (so they have `--apple_generate_dsym` and `--output_groups=+dsyms`), but we still want to generate an Xcode project to debug them from time to time. It would be nice if Tulsi can remove `dsyms` from the output groups (would `--output_groups=-dsyms` work?) when generating the project so we can avoid an unnecessary full build.
