### ISSUE TITLE
Build doesn't stop immediately when the user cancels the build

### ISSUE THREAD

**Issue by thii** [bazelbuild/tulsi#138]
Tulsi tries to gracefully exit on SIGINT it receives from Xcode when the
user stop the build. This oftentimes makes the next build stuck at
waiting for the previous build to finish, when the user starts a new
build right after canceling a build.

**Comment by DavidGoldman** [comment]
What issues are you seeing here? What is making the new build `stuck`?

**Comment by thii** [comment]
I saw a "Another command is running. Waiting for it to complete on the server..." for a second, then  it stuck at at the "Running /path/to/bazel build ...".

It seemed easier to reproduce if you cancel the build when it's in the middle of building a swift_library target.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
