### ISSUE TITLE
Any plans to support SwiftUI preview ?

### ISSUE THREAD

**Issue by ra1028** [bazelbuild/tulsi#143]
Currently, we can't enable SwiftUI preview on tulsi using bazel build system.

I believe that it's available with some tricks like adding build phase 'Compile Sources' manages target swift sources again and setting stub script to `SWIFT_EXEC`.

Maybe it's needed to pass `swiftmodule`s generated by bazel to swiftc with '-I' option, then Xcode can compile `preview-thunk.swift` to `preview-thunk.dylib`.

I think it's an essential feature for iOS app development now.

Thanks!

**Comment by tinder-maxwellelliott** [comment]
Where did you find these tips? I am looking at trying to get this working but it seems like you have some information on how to get this to work.

**Comment by DavidGoldman** [comment]
In its current form, Tulsi isn't compatible with previews since previews require proper buildable target/schemes (AFAIK limited to the active scheme). An alternative approach like [XCHammer](https://github.com/pinterest/xchammer) seems better suited  to let Xcode handle part of the build.

**Comment by ra1028** [comment]
@DavidGoldman 
Thank you for your response.
Do you mean that I would recommend using XCHammer? I tried that before, but it wasn't stable, so I'm using Tulsi now.
Does Tulsi have any plans to make improvements to support SwiftUI?

**Comment by Tomsons** [comment]
what if, I might be wrong, but creating a framework that holds sources and just creating a simple wrapper library for the App and Scene delegates could maybe do the trick to get previews in XCode?

**Comment by tinder-garricnahapetian** [comment]
Any news on adding support for this?

**Comment by sualehasif** [comment]
hoping for an update on this :)

**Comment by keith** [comment]
The future for this is likely for folks to use [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) which already supports this.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
