### ISSUE TITLE
Synchronize Xcode file tree with directory on the file system

### ISSUE THREAD

**Issue by ra1028** [bazelbuild/tulsi#144]
## Description

Files added from the Xcode source tree generated by tulsi are added to the project root.
I've found the same issue reported in the past.

Of course, I can understand that tulsi creating a dummy group to solve some issues, but I think it should be fixed to familiarize tulsi with general iOS developers using Xcode.

I suggest adding an option to enable this as an optional feature to the tulsi CLI to safely fix it.
Like, `tulsi --genconfig MyProject.tulsiproj --use-real-path`

## Related

https://github.com/bazelbuild/tulsi/issues/55
https://github.com/bazelbuild/tulsi/commit/68c0b2089939805b2a7c42c3b6c7bf941c9c3dc2
https://github.com/bilibili/tulsi/pull/1

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
