### ISSUE TITLE
Debugging is broken if --apple_generate_dsym isn't passed

### ISSUE THREAD

**Issue by BalestraPatrick** [bazelbuild/tulsi#147]
In trying to understand why LLDB doesn't stop on all breakpoints I set in a few of our projects (mostly 100% Objective-C), and it seems like passing `--apple_generate_dsym` as a build option is required. Judging from this (a bit old issue) https://github.com/bazelbuild/tulsi/issues/68, that shouldn't be the case for Objective-C only projects.

I also noticed that in a project with both Swift and Objective-C targets, `--apple_generate_dsym` isn't automatically added for the project like the docs describe: https://tulsi.bazel.build/docs/gettingstarted.html

Any idea if something broke or am I misinterpreting the docs?

**Comment by DavidGoldman** [comment]
This seems like a dupe of #88, perhaps Tulsi should automatically pass that linking flag to force locally to be unsandboxed. Or are you seeing this without sandboxing enabled?

**Comment by BalestraPatrick** [comment]
Yeah, I was expecting that to be the case by reading the docs. And yes, we have sandbox enabled.

**Comment by DavidGoldman** [comment]
I'm unsure if this should be in Tulsi - almost sounds like it would be better in a bazelrc file, but feel free to submit a PR to add this for debug builds.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
