### ISSUE TITLE
Xcode missing some source files

### ISSUE THREAD

**Issue by weinixuehao** [bazelbuild/tulsi#154]
![image](https://user-images.githubusercontent.com/17869361/85513062-365bf080-b62d-11ea-8477-99baa18ddfb6.png)
This is the selected folder

![image](https://user-images.githubusercontent.com/17869361/85511761-b5502980-b62b-11ea-95ea-2a337bc90f02.png)
The blue folder is one of the missing source file that i have manually added. Why missing these files?

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
