### ISSUE TITLE
Failure to build Xcode 12.0 beta 

### ISSUE THREAD

**Issue by yearofthewhopper** [bazelbuild/tulsi#156]
Hi, don't know if this is resolvable but the output states `/external/build_bazel_rules_swift/swift/internal/providers.bzl:261:1: Keyword-only argument is forbidden.` 
in Xcode 12.0 beta and tulsi fails to build.

upgrading Bazel fixed issue*

**Comment by ljmkimqx** [comment]
same error  xcode 11.4
