### ISSUE TITLE
The Tulsi crashed when the "tulsiproj" project was opened

### ISSUE THREAD

**Issue by ljmkimqx** [bazelbuild/tulsi#158]
environment：
mac system:  10.15.5
bazel:             3.4.0
xcode:            11.4.1(11E503a)
tulsi:               0.20190814.88

error:

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'launch path not accessible'
terminating with uncaught exception of type NSException
abort() called

Tulri "WORKSPACE" file edit:

tag = "0.17.4"  -> tag = "0.19.0",  like this

git_repository(
    name = "build_bazel_rules_apple",
    remote = "https://github.com/bazelbuild/rules_apple.git",
    tag = "0.19.0",
)

**Comment by keith** [comment]
Dup of https://github.com/bazelbuild/tulsi/issues/142
