### ISSUE TITLE
Module names are incorrect for indexing targets

### ISSUE THREAD

**Issue by michaeleisel** [bazelbuild/tulsi#163]
Indexing targets still need to have their normal module names or they won't build properly, but tulsi uses mangled module names with _idx at the start

**Comment by DavidGoldman** [comment]
Did you see any particular improvements? This came up [before](https://github.com/bazelbuild/tulsi/pull/23) but we didn't notice any major differences when testing, perhaps we missed something. Would just need to do something similar to how we handle [tests](https://github.com/bazelbuild/tulsi/blob/462dacf7f72d9420be566ed5251bacc17c41a5cb/src/TulsiGenerator/PBXTargetGenerator.swift#L1464).

**Comment by michaeleisel** [comment]
yeah just setting the module names to be what they would be with bazel makes sense

**Comment by tinder-maxwellelliott** [comment]
@Keith Why was #23 closed? Is this no longer an issue?

**Comment by keith** [comment]
likely is but that PR was very stale was all

**Comment by DavidGoldman** [comment]
Looks like this is more relevant in Xcode 13 as the module name is used to resolve the auto-import functionality

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
