### ISSUE TITLE
Generating a different Xcode project based on command line options

### ISSUE THREAD

**Issue by michaeleisel** [bazelbuild/tulsi#174]
I want to generate a project with an additional build argument without modifying any files. The `--build-options` option seems perfect, but when I use it, with `~/Applications/Tulsi.app/Contents/MacOS/Tulsi -- --bazel /path/to/bazel --genconfig /path/to/app.tulsiproj --no-open-xcode --build-options "asdf"`, it doesn't seem to have any effect. Why might this be? The project itself is just a trivial one, e.g. here's the BUILD file:
```
load("@build_bazel_rules_apple//apple:ios.bzl", "ios_application")

objc_library(
    name = "a",
    srcs = ["a.c"],
)

ios_application(
    name = "app",
    bundle_id = "com.example.app",
    families = ["iphone"],
    infoplists = [":Info.plist"],
    minimum_os_version = "11.0",
    deps = ["a"],
)
```

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
