### ISSUE TITLE
Xcode project should be relative to WORKSPACE

### ISSUE THREAD

**Issue by jerrymarino** [bazelbuild/tulsi#18]
The current Xcode project contains absolute paths in it. This unfortunately, makes Tulsi Xcode project not reusable across build nodes: they can't be shared among developers or CI machines.

My workflow involves checking in the Xcode project due to generation speed ( side effect from the aspect API, which requires a build https://github.com/bazelbuild/bazel/issues/3036 ). I'm effectively using git as a cache for these Xcode projects. To write Xcode projects that works seamlessly on any build node, I think eventually everything in the project should be a relative path.

I link a Bazel binary into the `WORKSPACE` - this makes it easy to manage Bazel versions across commits and have a sandboxed `WORKSPACE`. With this change in Tulsi, I can point tulsi at that relative path.

Also, Xcode projects conventionally contain only relative paths: an Xcode project doesn't have dependencies on user level or transient absolute paths.

I've already started to add this support, which gets an Xcode project that is somewhat shareable. The first commit towards a full relative Xcode project is a relative Bazel: https://github.com/pinterest/tulsi/pull/2 🚀 

Weather out not I will need 100% relative projects depends on what performance looks like for generating an Xcode project for the entire WORKSPACE: I may need to iterate more on this soon.

**Comment by steren** [comment]
Hi @jerrymarino, feel free to suggest this change upstream as a Pull Request on this repo. The team gladly welcomes contribution and will be able to review it.

**Comment by rahul-malik** [comment]
@steren - We've been using this locally and it seems to be working well. Can someone on the team take a look and provide feedback?

**Comment by steren** [comment]
@kelvinchan-google could you route the review of this PR to somebody in your team?

**Comment by steren** [comment]
CC @helenalt

**Comment by dmishe** [comment]
Hi Jerry, thanks for opening this.

I think I understand your desire for portable projects. As I said before, this is not a use case we plan to support so there is no guarantee that future changes won’t break them. Contributions are always welcomed though so please feel free to send patches in those situations.

You have also mentioned that you use the generated project on CI machines, is that right? Tulsi is meant for local development only, and any kind of CI environment should really be using Bazel.

**Comment by jerrymarino** [comment]
Hey @steren and @dmishe thanks for the comments and feedback. I totally understand not supporting this use case since you don't need it, thanks for being open to patches!

Originally, I think the generated project was used on CI to run units ( a few bazel versions ago, when `bazel test` was not working ). This shouldn't be needed with `bazel test` and I believe it works good in `5.2`

So the main use for portable projects checked in to the repo is not needing to regenerate the project constantly for local development. For me, this is useful in an environment where files are frequently added and removed.

**Comment by rahul-malik** [comment]
@dmishe - Your comment about CI machines would be true for us if there were test runners for integration tests through `bazel test`. Right now we rely on running them via XCode so we need a project to do that on CI.

**Comment by dmishe** [comment]
By running them through  Xcode, do you mean a Tulsi-generated Xcode project or something else? If it's indeed the former, then you by definition have the bazel binary and everything required for installed on that machine. Wouldn't it be easier to just run bazel test then?

**Comment by rahul-malik** [comment]
@dmishe - This works for logic based tests but not for UI / Integration tests because there isn't a test runner we can use afaik and it isn't scheduled until a much later Bazel release. Bazel test can execute logic tests written for XCTest but not XCUITest.

Our integration tests are actually written with EarlGrey which is XCTest under the hood so I was curious if Google is able to run EarlGrey tests internally via `bazel test`.

**Comment by DavidGoldman** [comment]
Closing this due to commit baadac6. 

Are you still seeing slow project generations? We've recently made some improvements, but as far as I'm aware we aren't compiling code during project generation (due to our usage of `output_groups`); feel free to open another issue if so.
