### ISSUE TITLE
Generating xcode project issues

### ISSUE THREAD

**Issue by weinixuehao** [bazelbuild/tulsi#184]
![Uploading image.png…]()
It hangs forever

**Comment by DavidGoldman** [comment]
Doesn't look like you uploaded an image, what step is getting stuck? Is it running Bazel?

**Comment by weinixuehao** [comment]
![image](https://user-images.githubusercontent.com/17869361/96063152-e483f280-0ec9-11eb-8a07-e5142c15ac23.png)
It hangs and never finishes.

**Comment by weinixuehao** [comment]
![image](https://user-images.githubusercontent.com/17869361/96067292-fa92b280-0ecb-11eb-95ca-b93356f4c6d6.png)
then to force quit to reopen the generate button is disabled

**Comment by weinixuehao** [comment]
![image](https://user-images.githubusercontent.com/17869361/96068661-1d729600-0ecf-11eb-923e-ccd15bd6d89a.png)
I try to run that cmd in the terminal which print "Waiting for is to complete no the server"

**Comment by weinixuehao** [comment]
`[10:30:05](3): Running /usr/local/bin/bazel --max_idle_secs=60 query '--override_repository=tulsi=/Users/user/Library/Application Support/Tulsi/0.20200917.88/Bazel' --announce_rc --noimplicit_deps --order_output=no --noshow_loading_progress --noshow_progress buildfiles(deps(//mediapipe/examples/ios/hededgedetectiongpu:HedEdgeDetectionApp)) --keep_going --output xml`

![image](https://user-images.githubusercontent.com/17869361/96069927-c7ebb880-0ed1-11eb-8a66-2848e7a59f6c.png)
It never finishes executing this cmd

**Comment by avartation** [comment]
![image](https://user-images.githubusercontent.com/36676864/113427939-fb21f580-93e6-11eb-84c0-8b5aa928b5de.png)
Any updates on this issue ?

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
