### ISSUE TITLE
Ease of Install: Brew Cask or Bazel Rule

### ISSUE THREAD

**Issue by cpsauer** [bazelbuild/tulsi#187]
Tulsi/Bazel folks, thanks for releasing a great tool to the world!

I was wondering if you'd consider making a brew cask for Tulsi. That'd make install and update even smoother.

Thanks,
Chris

**Comment by cpsauer** [comment]
Self editing: Maybe even better would be to just use bazel as the package manager, and to load tulsi from the WORKSPACE, like XCHammer intends to?

**Comment by cpsauer** [comment]
After some more thought, perhaps importing through WORKSPACE and generating/running via a rule would be equally easy but more in the spirit of bazel?

**Comment by thii** [comment]
You can add it to your WORKSPACE and run it with Bazel.

```
bazel run @build_bazel_tulsi//:tulsi -- -- [flags]
````

**Comment by cpsauer** [comment]
@thii's suggestion is totally the way to go. Thank you @thii!

As an example for anyone else reading, just add [rules_apple](https://github.com/bazelbuild/rules_apple) to your WORKSPACE, followed by a http_archive for tulsi. So at the time of writing:

```
http_archive(
    name = "build_bazel_tulsi",
    # Grabbing master for this example, so it always points to the latest. Do *not* add a sha256, or you'll break the autoupdate!
    urls = ["https://github.com/bazelbuild/tulsi/archive/master.zip"],
    strip_prefix = "tulsi-master"
)

# You may well need/want to bump this version. Check https://github.com/bazelbuild/tulsi/blob/master/WORKSPACE
http_archive(
    name = "build_bazel_rules_apple",
    sha256 = "734813e44eb5a2fcba5ffd45de9fe5d05325420a5aa1f6c97a3d88fe2c525b17",
    url = "https://github.com/bazelbuild/rules_apple/releases/download/0.21.1/rules_apple.0.21.1.tar.gz",
)
load("@build_bazel_rules_apple//apple:repositories.bzl", "apple_rules_dependencies")
apple_rules_dependencies()
load("@build_bazel_rules_swift//swift:repositories.bzl", "swift_rules_dependencies")
swift_rules_dependencies() # Needed for Tulsi. Seems to also pull in protobuf
load("@build_bazel_apple_support//lib:repositories.bzl", "apple_support_dependencies")
apple_support_dependencies()
```

Still think it'd be sweet if this were a more official way to install--perhaps with a starlark function to check for dependencies, rules_apple-style?

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
