### ISSUE TITLE
Ease of Install: Detect Installed Xcode (with sol'n)

### ISSUE THREAD

**Issue by cpsauer** [bazelbuild/tulsi#188]
Tulsi/Bazel folks, thanks again for releasing a great tool :)

One thing that surprised me on install was that it was trying to access an older hardcoded version of Xcode (11.7) rather than whatever's installed. Would you be open to making it just autodetect? A possible fix: This snippet should pull out the selected version number: `$(xcodebuild -version | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/')`. So `./build_and_run.sh -x $(xcodebuild -version | perl -pe '($_)=/([0-9]+([.][0-9]+)+)/')` just does the right thing, but we could also just set xcode_version to that in build_and_run.sh and no future users would have to worry about it. Is that something you'd accept a PR for? Maybe there's an important reason for the hardcode that I'm missing/

Separately, I was also pretty surprised it tried to install to ~/Applications, rather than the standard /Applications. Would you open to changing the default to /Applications?

Happy to submit PRs for one or both if you're open to 'em.

Thanks,
Chris

**Comment by keith** [comment]
@DavidGoldman what's the historical reason the Xcode version has always been locked?

**Comment by cpsauer** [comment]
Hey @keith! Thanks for you good advice to try these.

**Comment by cpsauer** [comment]
Wait, yeah, sorry. After looking back deeper at this, Keith is totally right that the real question is why Xcode is hardcoded at all, rather than just letting bazel autodetect it as usual. [Scratch my earlier, overly complex solution; was thinking the Xcode version was getting passed in a a custom flag rather than just to Bazel.]

**Comment by cpsauer** [comment]
I no longer need this (switched to loading in WORKSPACE at @thii's suggestion, see https://github.com/bazelbuild/tulsi/issues/187), but it still seems pretty user-unfriendly to turn off Xcode auto-detect.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
