### ISSUE TITLE
Configs override most project settings by default?

### ISSUE THREAD

**Issue by cpsauer** [bazelbuild/tulsi#192]
Hi Tulsi folks,

It seems like most project settings are default overridden by the defaults set in the config. Is this intentional? Unless I'm missing something--which I totally could be--this makes setting most project settings pointless, since they'd be always just be set back to the defaults by the config settings.

I would have expect something more like the Xcode levels view--which I think Tulsi's config interface is modeled on--where values are inherited unless explicitly set.

As a concrete example: Say you set the C++ language standard in the project. Configs seem to immediately shadow it with their default, rendering setting it at the project level pointless.

Thanks for your consideration!

**Comment by cpsauer** [comment]
...and a follow up: The per-target settings don't actually seem to be selectable. The behavior I'd expect is described in the docs (Setting options section of https://tulsi.bazel.build/docs/gettingstarted.html). The per target settings appear fine and have a dropdown icon but it's not clickable.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
