### ISSUE TITLE
[Question] Is there a way to have tulsi show all files in the workspace?

### ISSUE THREAD

**Issue by cpsauer** [bazelbuild/tulsi#193]
Hi! 

Is there a way to have all files in the workspace visible in Xcode? 

I can see the recursive options in the GUI, looked at the source, and played around with all kinds of variations on "..." for souceFilters in the configuration's tulsigen, but couldn't get it to work. It feels like there's got to be a way to do this based on the description in the [walkthrough](https://tulsi.bazel.build/docs/walkthrough.html), but I'm not seeing it.

Thanks so much,
Chris

**Comment by cpsauer** [comment]
Hacked on this for a little. Looks like the parsing of sourceFilters incorrectly assumes that ... recursive expansions are always preceded by a /, which would explain why this doesn't work. [Those assumptions are also carried over into the UI, which doesn't show the top level filter, it seems.]

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
