### ISSUE TITLE
Non-Deterministic Behavior: Files Randomly Omitted When Selecting on CPU Architecture

### ISSUE THREAD

**Issue by cpsauer** [bazelbuild/tulsi#197]
Hello Tulsi Folks,

After some workarounds, I thought I'd gotten tulsi behaving great. But then I noticed some very odd behavior indeed: The set of files added to Xcode isn't consistent between runs! 

Some files would get omitted on some runs. Hit generate again (with no changes) and they'd reappear.

To give a concrete example: I've narrowed down my case to select statements on CPU architecture. The files being randomly excluded are compiled only for ios_arm64. In my case, the deps are selected based on cpu, like in the following snippet (unimportant details omitted--just giving enough to get a test case):
```
# Imagine the following is a library included from an ios binary, like an ios_application or ios_framework
cc_library(
    ...
    deps = select({
        ":iOS-arm64": [":a"],
        "//conditions:default": [":b"],
    }),
)

config_setting(
    name = "iOS-arm64",
    values = {"cpu": "ios_arm64"},
)
```
In this example the source files from :a are randomly omitted between runs a significant fraction of the time. The source files from :b are *always* included, even when that doesn't make sense--more on that below.

The randomness seems to depend on which architectures are turned on. In my .bazelrc, I set the architectures with `build --ios_multi_cpus=armv7,arm64`. When I do that, the files are omitted about half the time. If I change things to build for only armv7, then :a is always omitted. If I change to just arm64 then :a is always included, as is :b, even though :b is never built for arm64 (!?). Adding more architectures seems to up the failure percentage. It's as though tulsi is randomly choosing an architecture to get sources for on each run--but also always including default options. (Shot in the dark: Race condition between parallel computation for each architecture, plus problematic handling of the default case?). If you want, happy to dig in more, if you'll point me to a place to learn more about the internals.

So to sum (TL;DR): Selecting on cpu leads to random omission of dependent files, except those in a default case. Instead, I'd expect the union of the files for each relevant case to show up in Xcode--just as Tulsi already beautifully handles multiple targets or multiple platforms.

Thanks for reading,
Chris
(ex-googler)

P.S. FWIW, none of these issues manifest if you select on apple_platform_type; selecting to differentiate between macOS and iOS seems to work fine. 

P.P.S. The project/config settings for "Bazel Apple platform and cpu for project generation" seem to have no impact--either on this or in general. I think they're just to configure cc or objc libraries that aren't being drawn in as a dependency of an ios_application/framework? (lmk if you know.) There's some strange behavior there--the project setting seems to be being used for all targets in the build command logged during project generation--but it doesn't seem to matter for our purposes here.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
