### ISSUE TITLE
Build with latest rules_swift is broken

### ISSUE THREAD

**Issue by comius** [bazelbuild/tulsi#199]
First failed build happened on 2020-12-02 at 3:02.
Link: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1796#760306b0-7f1d-43ad-9112-b1a6783fa448

Failing test: `src/TulsiGeneratorIntegrationTests/EndToEndGenerationTests` and `src/TulsiGeneratorIntegrationTests/AspectTests`

Error messages:
```
ERROR: /private/var/tmp/_bazel_buildkite/501ab27f0c0630bce26b2b26c96e7f8d/sandbox/darwin-sandbox/97/execroot/__main__/_tmp/6c0a7c9a6b92b2efb0a9070b1fc3ddf8/fake_execroot/__main__/tulsi_e2e_broken_build/BUILD:22:16: //tulsi_e2e_broken_build:Application: no such attribute 'lolno' in 'ios_application' rule
ERROR: error loading package 'tulsi_e2e_broken_build': Package 'tulsi_e2e_broken_build' contains errors
...
ERROR: /private/var/tmp/_bazel_buildkite/4387fe36974f2c35432a1477fa561eb4/sandbox/darwin-sandbox/95/execroot/__main__/_tmp/25ad511f3864a48b7f5a6ea9b9716e6f/fake_execroot/__main__/tulsi_test/BUILD:91:14: //tulsi_test:SubSwiftLibrary: missing value for mandatory attribute 'srcs' in 'swift_library' rule
ERROR: error loading package 'tulsi_test': Package 'tulsi_test' contains errors
```

I would say culprit is update of rules_swift:
https://github.com/bazelbuild/rules_swift/commits/master
My bet is commit 7fdbb717372911b87537b83fff86927217c6557b, but there might be a second one.

(I'm reporting this, because I'm monitoring bazel-at-head-plus-downstream)

**Comment by comius** [comment]
friendly ping

**Comment by keith** [comment]
Looking into this here https://github.com/bazelbuild/tulsi/pull/201

**Comment by c-parsons** [comment]
Tulsi seems broken at HEAD still. Not sure if it was fixed and then broke again, but I see the error is a bit different now:

https://buildkite.com/bazel/tulsi-bazel-darwin/builds/1195#2f153bd6-6abc-4f72-afb3-4748b2ebf273

```
(23:16:26) ERROR: /Users/buildkite/builds/bk-imacpro-2/bazel/tulsi-bazel-darwin/src/TulsiGenerator/BUILD:30:14: in @build_bazel_rules_apple//apple/internal/aspects:resource_aspect.bzl%apple_resource_aspect aspect on swift_library rule //src/TulsiGenerator:tulsi_generator_lib:
--
  | Traceback (most recent call last):
  | File "/private/var/tmp/_bazel_buildkite/3301f1ad62fbea3aa42652da3e602ce4/external/build_bazel_rules_apple/apple/internal/aspects/resource_aspect.bzl", line 96, column 59, in _apple_resource_aspect_impl
  | bucketize_args["swift_module"] = target[SwiftInfo].module_name
  | Error: 'SwiftInfo' value has no field or method 'module_name'
```

**Comment by keith** [comment]
Hrm, I'm not sure if this was intentional but this is part of that issue https://github.com/bazelbuild/tulsi/pull/209

**Comment by keith** [comment]
This should be fixed on master now, lmk if you see more failures!

**Comment by keith** [comment]
https://github.com/bazelbuild/tulsi/pull/203
