### ISSUE TITLE
Running build_and_run.sh issue 

### ISSUE THREAD

**Issue by ozgurshn** [bazelbuild/tulsi#204]
Running this command sh build_and_run.sh results with the error below and does not install Tulsi.app. I'm using Xcode 12.2. Could anyone help with this issue?
Unrecognized option: --use_top_level_targets_for_symlinks

**Comment by thii** [comment]
What Bazel version are you using?

**Comment by ozgurshn** [comment]
I forgot to update bazel, it was very old. Updating it fixed the issue. Thanks.
