### ISSUE TITLE
BES parser reads uri as path without decoding it

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/tulsi#205]
Bazel [allows][1] some of the `\W` characters in the label name, which will be percent-encoded in the build event stream. The BES parser is not decoding those percent-encoded characters ATM:

https://github.com/bazelbuild/tulsi/blob/b965114f31a464185318c71ef3d0c1538d0c52de/src/TulsiGenerator/BazelBuildEvents.swift#L27-L32

and causes execution error:

> [10:21:25 AM](1): Failed to parse information about supported target in '/private/var/tmp/&lt;redacted&gt;/bazel-out/ios_x86_64-dbg/bin/WatchKit2%20Extension/&lt;redacted&gt;.tulsiinfo'. This is a Tulsi or Bazel bug, please report. Debug info: The file could not be read

[1]: https://docs.bazel.build/versions/master/build-ref.html#name

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
