### ISSUE TITLE
Use GH Releases to version updates to Tulsi

### ISSUE THREAD

**Issue by rahul-malik** [bazelbuild/tulsi#21]
Currently there are 0 releases of Tulsi so we've been building directly off of the latest master. 
- The difficulty with this is that we are unsure what version of Bazel is compatible with the latest Tulsi changes. 
- It would be helpful to understand the future roadmap / plans for Tulsi so we can contribute patches and features that are inline with the overall direction of the project.
- It is unclear what version of `rules_apple` is compatible with the latest Tulsi changes and when it is okay to update either project.

@steren for coordination

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
