### ISSUE TITLE
Tulsi cannot be opened on Mac OS 11.2 with xcode 12.4

### ISSUE THREAD

**Issue by useame** [bazelbuild/tulsi#222]
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10827 "kLSNoExecutableErr: The executable is missing" UserInfo={_LSLine=3665, _LSFunction=_LSOpenStuffCallLocal}

**Comment by lig-jaimejazarenoiii** [comment]
Same 😢

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
