### ISSUE TITLE
Tulsi swift_test support

### ISSUE THREAD

**Issue by tinder-cwybranowski** [bazelbuild/tulsi#224]
Hello! I've been experimenting with Tulsi for Swift CLI tooling development, and I noticed that it doesn't currently support [swift_test](https://github.com/bazelbuild/rules_swift/blob/9d472c1a0124a2f06ee234ce64fa174cba0637c9/swift/swift.bzl#L81) targets. Although there is a workaround (described below), it would be awesome to see support for this target type.

---

### Setup
- Bazel 4.0.0
- Xcode 12.4

---

### Demo Repository
I've created a public repository that demonstrates this issue, and a couple others related to `.tulsigen` configuration file generation: [tulsi-swift-test-demo](https://github.com/tinder-cwybranowski/tulsi-swift-test-demo).

Everything should be detailed in the `README` of that repository, but I'll post some information below for visibility.

---

### swift_test support
Although Tulsi appears to handle [swift_library](https://github.com/bazelbuild/rules_swift/blob/9d472c1a0124a2f06ee234ce64fa174cba0637c9/swift/swift.bzl#L80) targets correctly, it fails to generate a Tulsi project for [swift_test](https://github.com/bazelbuild/rules_swift/blob/9d472c1a0124a2f06ee234ce64fa174cba0637c9/swift/swift.bzl#L81) targets.

Here is the `BUILD` file, copied from the [demo repository](https://github.com/tinder-cwybranowski/tulsi-swift-test-demo) linked above:
```
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library", "swift_test")

swift_library(
    name = "DemoTarget",
    srcs = glob(["Sources/*.swift"]),
    module_name = "DemoTarget",
    visibility = ["//visibility:public"]
)

swift_test(
    name = "DemoTargetTests",
    srcs = glob(["Tests/*.swift"]),
    deps = [":DemoTarget"]
)
```

Here is the warning we receive after executing the `--genconfig` command:
```
[Error] Generate[FAIL]: 10.6267s Unsupported target type: swift_test (target //demo-target:DemoTargetTests)
Xcode project generation failed
```

In order to fix this temporarily, we have to define new [swift_library](https://github.com/bazelbuild/rules_swift/blob/9d472c1a0124a2f06ee234ce64fa174cba0637c9/swift/swift.bzl#L80) and [macos_unit_test](https://github.com/bazelbuild/rules_apple/blob/5819dc78d9233dce35d546f7a69690f075bbf1e5/apple/macos.bzl#L310) libraries for this test target:
```
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")
load("@build_bazel_rules_apple//apple:macos.bzl", "macos_unit_test")

swift_library(
    name = "DemoTargetTestsLibrary",
    srcs = glob(["Tests/*.swift"]),
    deps = [":DemoTarget"]
    module_name = "DemoTargetTestsLibrary",
    visibility = ["//visibility:private"],
)

macos_unit_test(
    name = "DemoTargetTests",
    deps = [":DemoTargetTestsLibrary"],
    minimum_os_version = "10.15",
    visibility = ["//visibility:public"]
)
```

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.

**Comment by tinder-cwybranowski** [comment]
> Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.

Forgot about this issue -- we've already migrated to `rules_xcodeproj` everywhere, so no problem at all.
