### ISSUE TITLE
Tulsi@head with Bazel@head is failing

### ISSUE THREAD

**Issue by comius** [bazelbuild/tulsi#225]
Error:
```
ERROR: /private/var/tmp/_bazel_buildkite/c013bd6eb8b7bb1baa33f065b8ba58c2/external/build_bazel_rules_apple/tools/xctoolrunner/BUILD:3:10:
Reporting failed target @build_bazel_rules_apple//tools/xctoolrunner:xctoolrunner located at 
/private/var/tmp/_bazel_buildkite/c013bd6eb8b7bb1baa33f065b8ba58c2/external/build_bazel_rules_apple/tools/xctoolrunner/BUILD:3:10 [for host] failed: 
@build_bazel_rules_apple//tools/xctoolrunner:xctoolrunner: 
This target is being built for Python 2 but (transitively) includes Python 3-only sources. You can get diagnostic information
 about which dependencies introduce this version requirement by running the `find_requirements` aspect. If this is used in 
a genrule, you may need to migrate from tools to exec_tools. For more info see the documentation for the `srcs_version` 
attribute: https://docs.bazel.build/versions/master/be/python.html#py_binary.srcs_version caused by 

@build_bazel_rules_apple//tools/xctoolrunner:xctoolrunner
```

Link: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1945#0bc1d4fd-12d2-4e3f-80db-99d675dacc91

Autosheriff is reporting infra change, but this is probably wrong.

Also: Tulsi@head is failing it appears to be due to https://github.com/bazelbuild/tulsi/commit/240913af549a53008931f062aea48deb2a2b57cd.

**Comment by comius** [comment]
cc @philwo @meteorcloudy

**Comment by meteorcloudy** [comment]
But 240913a was green in previous build:
https://buildkite.com/bazel/tulsi-bazel-darwin/builds/1297

So it does looks some infra has changed, @philwo Did we update our macOS machines recently?

**Comment by meteorcloudy** [comment]
Ah, the  "Latest Bazel with Head Deps on :mac: (OpenJDK 8)" job updates Tulsi's dependencies to the latest commit, see
https://github.com/bazelbuild/tulsi/blob/master/.bazelci/update_workspace_to_deps_heads.sh

And in rules_apple, they recently submitted a change to move the python3 only: https://github.com/bazelbuild/rules_apple/commit/72d27d5f0de8b455d23bfdfaeba7e6b1c2e91a42

/cc @DavidGoldman
