### ISSUE TITLE
Support setting "Siri Intent Query" from an Intents app extension scheme

### ISSUE THREAD

**Issue by thii** [bazelbuild/tulsi#235]
A normal Xcode scheme for an Intents app extension has this option, while the Tulsi generated one doesn't.

---
Normal Xcode scheme

<img width="930" alt="Screen Shot 2021-03-17 at 13 18 39" src="https://user-images.githubusercontent.com/4506500/111414623-a4989400-8723-11eb-87b6-c45a2c98818d.png">

---

Tulsi generated scheme

<img width="927" alt="Screen Shot 2021-03-17 at 13 17 38" src="https://user-images.githubusercontent.com/4506500/111414632-a82c1b00-8723-11eb-9804-077b66ce2a60.png">

**Comment by keith** [comment]
If you diff that scheme with a normal one is there a clear section that it's missing? I feel like I debugged this for XcodeGen in the past

**Comment by thii** [comment]
If the field is empty, there's no difference. If it's not empty, this setting is added to the `LaunchAction` section:

```
      intentQueryString = "Send Hi via App"
```

But manually adding that doesn't make that field show up. Xcode seems to also look at somewhere else.

**Comment by Jeremy-JM** [comment]
> If the field is empty, there's no difference. If it's not empty, this setting is added to the `LaunchAction` section:
> 
> ```
>       intentQueryString = "Send Hi via App"
> ```
> 
> But manually adding that doesn't make that field show up. Xcode seems to also look at somewhere else.



> If the field is empty, there's no difference. If it's not empty, this setting is added to the `LaunchAction` section:
> 
> ```
>       intentQueryString = "Send Hi via App"
> ```
> 
> But manually adding that doesn't make that field show up. Xcode seems to also look at somewhere else.

Do you have any solution for this?

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
