### ISSUE TITLE
External projects don't resolve sources properly

### ISSUE THREAD

**Issue by mikelikespie** [bazelbuild/tulsi#24]
They get set to the path "../Foo" instead of "bazel-projname/external/Foo". Looks like there's some support in tulsi for detecting external projects and even renamiong the group to be pretty like `@Foo/` in xcode, but it doesn't appear to be working.

This can be reproduced in this project/sha (tulsiproj included) https://github.com/mikelikespie/swiftled/commit/2c5f30efd619722ef78a21f2491dbe8974ae7d13

**Comment by DavidGoldman** [comment]
Hi Mike!

Thanks for reporting this issue and including a test project. Is this a new issue or have you always had problems with this?

**Comment by mikelikespie** [comment]
I think I was experiencing this a few months ago as well as recently. 

This is a super hacky workaround https://github.com/mikelikespie/tulsi/commit/c2b08ae0aa4a78d9d540c4a9b1f789356336eef2

**Comment by mikelikespie** [comment]
@DavidGoldman @dmishe thanks for the fix! just tested on my test project and it seems to work perfectly!
