### ISSUE TITLE
apple_static_framework_import generates invalid build settings

### ISSUE THREAD

**Issue by dflems** [bazelbuild/tulsi#245]
If a `swift_library` depends on a `apple_static_framework_import`, the idx target properly gets the framework's containing directory added to `FRAMEWORK_SEARCH_PATHS`, but it also gets an unnecessary `-fmodule-map-file` entry in `OTHER_SWIFT_FLAGS` (like `-Xcc -fmodule-map-file=path/to/My.framework/Modules/module.modulemap`). This explicit module map inclusion is unnecessary (just the framework path is enough for xcode to find the modulemap).

Test targets only get the invalid `-fmodule-map-file` and not the `FRAMEWORK_SEARCH_PATHS` entry.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
