### ISSUE TITLE
was not able to extract the execution root from workspace

### ISSUE THREAD

**Issue by WHChaw** [bazelbuild/tulsi#249]
![image](https://user-images.githubusercontent.com/14286720/121185421-a2645280-c898-11eb-9229-7d0b985f98aa.png)

**Comment by WHChaw** [comment]
my xcode version is 12.5

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
