### ISSUE TITLE
Generated files from external projects don't resolve correctly

### ISSUE THREAD

**Issue by mikelikespie** [bazelbuild/tulsi#25]
Bug is similar to https://github.com/bazelbuild/tulsi/issues/24, but with external genfiles.

Paths for genfiles from external projects are not being configured correctly as seen here:.

<img width="926" alt="swiftled_xcodeproj" src="https://user-images.githubusercontent.com/21435/28558270-073a1278-70c6-11e7-8709-6d97b70d0683.png">

Can repro it with this project/sha and the tulsiproj included: https://github.com/mikelikespie/swiftled/commit/c7a0a1e52b404a6f7bea3c8356fcc937961023a0

This is with latest master of tulsi.

**Comment by DavidGoldman** [comment]
Hey Mike! Thanks for reporting this. Did your ".." patch from #24 have this issue too? Looks like we'll need to special case external genfiles too.

**Comment by mikelikespie** [comment]
I think would have it too. Haven't actually tried, but I didn't do anything special to address the genfiles.

**Comment by DavidGoldman** [comment]
Are you still having this issue?

**Comment by mikelikespie** [comment]
I believe it is still an issue, however, I have moved on in my employment. Last I checked there were issues with both j2objc sources for local and external as which are in the bazel-bin as well as sources for protos which are in the genfiles. FWIW weren’t actively using tulsi right now so not huge urgency for us on the fix probably

**Comment by keith** [comment]
feel free to open a new issue if this is still the case
