### ISSUE TITLE
install tulsi failed on macOS

### ISSUE THREAD

**Issue by sek790c** [bazelbuild/tulsi#250]
Mac os 10.13.6 
bazel 4.1.0

liuchiyudeMacBook-Pro:tulsi lcy$ sh build_and_run.sh
Starting local Bazel server and connecting to it...
Analyzing: target //:tulsi (44 packages loaded, 217 targets configured)
    Fetching @local_config_cc; fetching 99s

after 105s, I got this:

liuchiyudeMacBook-Pro:tulsi lcy$ sh build_and_run.sh
Starting local Bazel server and connecting to it...
ERROR: /private/var/tmp/_bazel_lcy/5c49963cb3cdabd3637667642b95bec0/external/local_config_cc/BUILD:48:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'darwin_x86_64'

I could not solve the problem for a long time. I come from China, is this a network problem? How can I find this "@local_config_cc"

**Comment by keith** [comment]
Bazel issue so tracking on https://github.com/bazelbuild/bazel/issues/13589

**Comment by sek790c** [comment]
I open the BUILD file described in  Error. BUILD:
cc_toolchain_suite(
    name = "toolchain",
    toolchains = {
        "darwin|clang": ":cc-compiler-darwin",
        "darwin": ":cc-compiler-darwin",
        "armeabi-v7a|compiler": ":cc-compiler-armeabi-v7a",
        "armeabi-v7a": ":cc-compiler-armeabi-v7a",
    },
)
there is no toolchain for  darwin_x86_64
I open .bazelrc and rename build --cpu=darwin_x86_64 to build --cpu=darwin, still the same problem
what should i do?
