### ISSUE TITLE
Xcode 12.5 

### ISSUE THREAD

**Issue by SnailLoveSmile** [bazelbuild/tulsi#252]

**Comment by SnailLoveSmile** [comment]
(base)  ✘ apple@iMac  ~/Desktop/tulsi   master  sed -i .orig '/xcode_version/d' .bazelrc
(base)  apple@iMac  ~/Desktop/tulsi   master  sh build_and_run.sh
INFO: Repository build_bazel_rules_apple instantiated at:
  /Users/apple/Desktop/tulsi/WORKSPACE:3:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_apple/54b5ba87e899fcc28230c63f1537c127/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://github.com/bazelbuild/rules_apple/releases/download/0.31.2/rules_apple.0.31.2.tar.gz failed: class java.io.IOException Proxy address 127.0.0.1:1181 is not a valid URL
ERROR: An error occurred during the fetch of repository 'build_bazel_rules_apple':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_apple/54b5ba87e899fcc28230c63f1537c127/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.31.2/rules_apple.0.31.2.tar.gz] to /private/var/tmp/_bazel_apple/54b5ba87e899fcc28230c63f1537c127/external/build_bazel_rules_apple/temp11848012629932969873/rules_apple.0.31.2.tar.gz: Proxy address 127.0.0.1:1181 is not a valid URL
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_apple/54b5ba87e899fcc28230c63f1537c127/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.31.2/rules_apple.0.31.2.tar.gz] to /private/var/tmp/_bazel_apple/54b5ba87e899fcc28230c63f1537c127/external/build_bazel_rules_apple/temp11848012629932969873/rules_apple.0.31.2.tar.gz: Proxy address 127.0.0.1:1181 is not a valid URL
ERROR: no such package '@build_bazel_rules_apple//apple': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.31.2/rules_apple.0.31.2.tar.gz] to /private/var/tmp/_bazel_apple/54b5ba87e899fcc28230c63f1537c127/external/build_bazel_rules_apple/temp11848012629932969873/rules_apple.0.31.2.tar.gz: Proxy address 127.0.0.1:1181 is not a valid URL
INFO: Elapsed time: 12.794s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)




What should I do to fix it, thanks

**Comment by thii** [comment]
Seems like a problem with your proxy configuration.

**Comment by tinder-maxwellelliott** [comment]
> (base)  ✘ apple@iMac  ~/Desktop/tulsi   master  sed -i .orig '/xcode_version/d' .bazelrc
> 
> (base)  apple@iMac  ~/Desktop/tulsi   master  sh build_and_run.sh
> 
> INFO: Repository build_bazel_rules_apple instantiated at:
> 
>   /Users/apple/Desktop/tulsi/WORKSPACE:3:13: in <toplevel>
> 
> Repository rule http_archive defined at:
> 
>   /private/var/tmp/_bazel_apple/54b5ba87e899fcc28230c63f1537c127/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
> 
> WARNING: Download from https://github.com/bazelbuild/rules_apple/releases/download/0.31.2/rules_apple.0.31.2.tar.gz failed: class java.io.IOException Proxy address 127.0.0.1:1181 is not a valid URL
> 
> ERROR: An error occurred during the fetch of repository 'build_bazel_rules_apple':
> 
>    Traceback (most recent call last):
> 
> 	File "/private/var/tmp/_bazel_apple/54b5ba87e899fcc28230c63f1537c127/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
> 
> 		download_info = ctx.download_and_extract(
> 
> Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.31.2/rules_apple.0.31.2.tar.gz] to /private/var/tmp/_bazel_apple/54b5ba87e899fcc28230c63f1537c127/external/build_bazel_rules_apple/temp11848012629932969873/rules_apple.0.31.2.tar.gz: Proxy address 127.0.0.1:1181 is not a valid URL
> 
> ERROR: Error fetching repository: Traceback (most recent call last):
> 
> 	File "/private/var/tmp/_bazel_apple/54b5ba87e899fcc28230c63f1537c127/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
> 
> 		download_info = ctx.download_and_extract(
> 
> Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.31.2/rules_apple.0.31.2.tar.gz] to /private/var/tmp/_bazel_apple/54b5ba87e899fcc28230c63f1537c127/external/build_bazel_rules_apple/temp11848012629932969873/rules_apple.0.31.2.tar.gz: Proxy address 127.0.0.1:1181 is not a valid URL
> 
> ERROR: no such package '@build_bazel_rules_apple//apple': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.31.2/rules_apple.0.31.2.tar.gz] to /private/var/tmp/_bazel_apple/54b5ba87e899fcc28230c63f1537c127/external/build_bazel_rules_apple/temp11848012629932969873/rules_apple.0.31.2.tar.gz: Proxy address 127.0.0.1:1181 is not a valid URL
> 
> INFO: Elapsed time: 12.794s
> 
> INFO: 0 processes.
> 
> FAILED: Build did NOT complete successfully (0 packages loaded)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> What should I do to fix it, thanks

This can help with your proxy settings. https://github.com/bazelbuild/bazel/issues/5185

This is no longer a Tulsi issue, this error is from Bazel itself

**Comment by SnailLoveSmile** [comment]
Thank you very much @tinder-maxwellelliott

**Comment by tinder-maxwellelliott** [comment]
@SnailLoveSmile can you close this ticket? Its not a Tulsi issue

**Comment by SnailLoveSmile** [comment]
> @SnailLoveSmile can you close this ticket? Its not a Tulsi issue

I don't know exactly how to operate it.  thanks so much
