### ISSUE TITLE
ipad family is not selected in generated project

### ISSUE THREAD

**Issue by sergd2005** [bazelbuild/tulsi#253]
Hi, I am generating a project for the bazel tutorial project  https://docs.bazel.build/versions/main/tutorial/ios-app.html 
as you can see families field for ios_application rule is set to iphone and ipad
[build file](https://github.com/bazelbuild/examples/blob/master/tutorial/ios-app/BUILD)
however generated project selects only iphone family
<img width="1195" alt="Screen Shot 2021-07-08 at 5 38 03 PM" src="https://user-images.githubusercontent.com/6848947/124951139-5e897800-e013-11eb-8c74-d051ef66dcc4.png">

commit version of tulsi repo 937326ef Update rules_apple

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
