### ISSUE TITLE
Messages from the compiler not appearing on the editor on Xcode13 beta

### ISSUE THREAD

**Issue by rsahara** [bazelbuild/tulsi#262]
Expected:
<img width="1527" alt="スクリーンショット 2021-07-21 15 39 57" src="https://user-images.githubusercontent.com/12640489/126446850-d266777c-4e85-4c32-9e3c-db853136b5dc.png">

What we have on Xcode 13 (beta1 .. beta3):
<img width="1420" alt="スクリーンショット 2021-07-21 15 46 32" src="https://user-images.githubusercontent.com/12640489/126447035-86f33b32-35a3-4f90-8c52-7495e1f4e83c.png">

Error log:

```
/private/var/tmp/_bazel_JP22226/4400ae6b47bcd7e9d38c1b169afa2db3/execroot/app-name/path/to/file.swift:80:24: error: cannot find type 'CLLocation' in scope
        imageLocation: CLLocation?,
                       ^~~~~~~~~~
```

We don't have this problem on Xcode 12.5.

I checked that replacing the file path in the messages (`/private/var/tmp/_bazel_JP22226/4400ae6b47bcd7e9d38c1b169afa2db3/execroot/app-name/path/to/file.swift`)
with the file path of the source file in the workspace (`/Users/JP22226/workspace-dir/path/to/file.swift`.) may solve this problem. (I did some tests with some hardcoded path substitution in bazel_build.py.)

**Comment by rsahara** [comment]
After some investigation, it's more likely a problem with rules_swift (or somewhere else).

Error messages:
- ObjC file on Xcode13: local path.
- Swift file on Xcode13: full path.
- ObjC file on Xcode12.5: local path.
- Swift file on Xcode12.5: local path.

**Comment by keith** [comment]
Thanks for investigating, re-filed here https://github.com/bazelbuild/rules_swift/issues/new
