### ISSUE TITLE
Cannot debug with source files from "git_repository"

### ISSUE THREAD

**Issue by Ayatuas** [bazelbuild/tulsi#265]
I cannot debug with external dependencies of source file from git_repository.
Everything works well with local files,but I cannot STEP INTO external dependencies where breakpoint is set. An external dependent is like
![image](https://user-images.githubusercontent.com/28378181/127150978-3b6a2b33-410f-4320-a05d-386455fff465.png)
Any ideas?

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
