### ISSUE TITLE
Fail to run ios_ui_test target on device

### ISSUE THREAD

**Issue by rgnns** [bazelbuild/tulsi#266]
Works fine when running App on device or any target on Simulator, but fails when running UITests on device.

Failure reads:

/Users/gl/chaos/src/prototype-player/client/ios:0: Failed to extract Authority from Executable=<...>/Library/Developer/Xcode/DerivedData/app_uitests-dwpmonsrcnhlqpcszsglndmnoour/Build/Products/__TulsiTestRunner_Debug-iphoneos/app_uitests-Runner.app/PlugIns/app_uitests.xctest/app_uitests

Showing Recent Messages
Identifier=com.tester.ios-ui-app-hostTests
Format=bundle with Mach-O thin (arm64)
CodeDirectory v=20400 size=1159 flags=0x2(adhoc) hashes=29+3 location=embedded
Signature=adhoc
Info.plist entries=17
TeamIdentifier=not set
Sealed Resources version=2 rules=10 files=3
Internal requirements count=0 size=12

Running Xcode 12.5.1, bazel 4.1.0-homebrew, and tulsi built from HEAD (937326ef)

**Comment by wendyliga** [comment]
got the same error, but because no code sign was detected on the binary.

are there any reasons we don't provide codesign on `ios_ui_test` and `ios_unit_test`?

**Comment by wendyliga** [comment]
> got the same error, but because no code sign was detected on the binary.
> 
> are there any reasons we don't provide codesign on `ios_ui_test` and `ios_unit_test`?

i've solved the issue with defining `test_host` on BUILD and `--cpu=ios_arm64` to explicitly build for device

**Comment by wendyliga** [comment]
<img width="505" alt="Screen Shot 2022-08-10 at 10 49 58" src="https://user-images.githubusercontent.com/16457495/183808955-891edacd-3514-468f-a37e-f8708eebcc2a.png">

**Comment by kkpattern** [comment]
> got the same error, but because no code sign was detected on the binary.
> 
> are there any reasons we don't provide codesign on `ios_ui_test` and `ios_unit_test`?

`ios_unit_test` has `provisioning_profile` attr like `ios_application`. We are able to run unit tests on devices after providing this. It seems not documented.

**Comment by wendyliga** [comment]
> > got the same error, but because no code sign was detected on the binary.
> > are there any reasons we don't provide codesign on `ios_ui_test` and `ios_unit_test`?
> 
> `ios_unit_test` has `provisioning_profile` attr like `ios_application`. We are able to run unit tests on devices after providing this. It seems not documented.

indeed, thanks for the info @kkpattern

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
