### ISSUE TITLE
Archive action on ios_application target provides invalid xcarchive

### ISSUE THREAD

**Issue by rahul-malik** [bazelbuild/tulsi#27]
I'm currently using the `rules_apple` rules with Tulsi to define our iOS application. Building and running on device works and creates a valid IPA but using archive seems to quickly produce an invalid archive.

Any ideas on how to address this?

**Comment by mpalczew** [comment]
Anything on this one. Without being able to build an archive how do you get it to the App Store.

**Comment by keith** [comment]
We use the ipa produced with Bazel build for this. In what ways is the archive from tulsi invalid?

**Comment by xiemotongye** [comment]
Now we’re using ```altool``` to upload our application to the App Store. But without xcarchive file, we cannot use some further feature such as Getting an App Size Report(see in https://developer.apple.com/library/archive/qa/qa1795/_index.html) which could estimate app size before uploading to App Store.

**Comment by keith** [comment]
At this point creating xcarchives from tulsi is unsupported, produce them with `bazel build //your:target` instead.

**Comment by Takuro-Ito** [comment]
> At this point creating xcarchives from tulsi is unsupported, produce them with `bazel build //your:target` instead.

Any plans to support Xcode Archive?

**Comment by keith** [comment]
Do you have a use case where building with bazel directly doesn't work?

In general it might be possible but I don't think it's something we'd jump on

**Comment by Takuro-Ito** [comment]
Thanks for very quick response.

In my case, I create ***tulsi generated .xcodeproj*** which contains `ios_static_framework` target.
And another ***Main App .xcodeproj*** contains **this** ***tulsi generated .xcodeproj*** and links with `ios_static_framework` target.
Xcode Build & Run works fine as expected, but Xcode Archive fails when building as `ios_static_framework` is not linked correctly.

I know ***Main App .xcodeproj*** can be archived if ***`bazel build` generated .framework*** is linked because this `.framework` contains all resources like headers. But it would be awesome if we directly perform `Xcode Archive` with ***tulsi generated `ios_static_framework`***!

**Comment by kkpattern** [comment]
> Do you have a use case where building with bazel directly doesn't work?
> 
> In general it might be possible but I don't think it's something we'd jump on

@keith We want to use tulsi to archive too. The use case is to max cache hit. We want the release build to share the cache with the development build.

**Comment by keith** [comment]
That's not really feasible in general. At the very least changing the `--compilation_mode` between release builds and debug builds to make sure you get the best debug build performance for debug, and the best app size and runtime performance for release, will entirely invalidate the cache.

**Comment by kkpattern** [comment]
> That's not really feasible in general. At the very least changing the `--compilation_mode` between release builds and debug builds to make sure you get the best debug build performance for debug, and the best app size and runtime performance for release, will entirely invalidate the cache.

We also use release during development a lot because debug mode sometimes is too slow for our app(a mobile game). That's why we also create this issue https://github.com/bazelbuild/tulsi/issues/352 .

**Comment by kkpattern** [comment]
Also, it's very attractive to be able to open XCode and debug the exact same binary that is released to users.

**Comment by keith** [comment]
Oh interesting! Do you not have anything else that changes and invalidates the cache? We have many other things that differ between release and debug compiles as well, that was just the first one I jumped to. Theoretically you could still craft a similar `bazel` CLI command to mirror what tulsi is doing

**Comment by kkpattern** [comment]
> Theoretically you could still craft a similar `bazel` CLI command to mirror what tulsi is doing

Definitely. That's what we are trying to do now. It's just better to have a single source of truth for the build configs. On the other hand, we don't need tulsi to do the archive actually. Maybe we can add a script to return the build configs tulsi will use, then we can use to generate ipa with bazel build. Something like:

```bash
bazel build //target $(/path/to/xcodeproject/.tulsi/Script/build_config.py --release)
```
