### ISSUE TITLE
Entitlements not included when generating with Tulsi

### ISSUE THREAD

**Issue by akshaygarg-TUL-Luxury** [bazelbuild/tulsi#275]
while generating ios_application with Tulsi, entitlements are not included in the generated project.

```
ios_application(
    name = "MyApp",
    bundle_id = "MyApp.Example",
    entitlements = "//MyApp:Entitlement",
    infoplists = [
        "//MyApp/Info.plist"
    ],
    minimum_os_version = "11.0",
    families = ["iphone"],
    deps = ["Sources"],
    linkopts = [
        '-lxml2',
        '-lz',
        '-ObjC'
    ]
)

filegroup(
    name = 'Entitlement',
    srcs = [
        'MyApp.entitlements'
    ]
)
```

**Comment by lucasmpaim** [comment]
Same problem here, did you found some workaround?

**Comment by akshayg13** [comment]
> Same problem here, did you found some workaround?

not yet
Please let me know if u find anything

**Comment by thii** [comment]
You mean the pre-processed ones? You can add them via the `additionalFilePaths` in your tulsigen.

**Comment by thii** [comment]
Add the path to that file to your tulsigen file, for example:
https://github.com/bazelbuild/tulsi/blob/c7609aa3914123f1b5f1a6b5caff551617a325c9/Tulsi.tulsiproj/Configs/Tulsi.tulsigen#L32-L34

**Comment by akshayg13** [comment]
> Add the path to that file to your tulsigen file, for example:
> 
> https://github.com/bazelbuild/tulsi/blob/c7609aa3914123f1b5f1a6b5caff551617a325c9/Tulsi.tulsiproj/Configs/Tulsi.tulsigen#L32-L34

@thii even after adding the file path to `additionalFilePaths`, entitlements are not included in the generated project

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
