### ISSUE TITLE
Swift breakpoints are only stopping the code

### ISSUE THREAD

**Issue by lucasmpaim** [bazelbuild/tulsi#276]
In my project breakpoints can stop my code execution, but I can't see any variable value, everything says: `error: cannot find '<variable>' in scope`

<img width="1158" alt="Captura de Tela 2021-10-13 às 18 21 49" src="https://user-images.githubusercontent.com/7849484/137214314-eda7e42f-4e26-4a38-bdc2-1ce73dffee39.png">

I have tried on `AppDelegate`, `<Any>ViewController:viewDidLoad` etc.

This happen's on both Simulator and real devices in M1 and Intel Macbook's.

My `.bazelrc` file:

```text
build --genrule_strategy=standalone
build --spawn_strategy=standalone
build --verbose_failures
build --test_output=errors
build --strategy=SwiftCompile=standalone
build --apple_generate_dsym
```

Bazel Version: 4.2.1-homebrew
Tulsi Version: Commit ~63bab0db

Possible related issue: #15

**Comment by DavidGoldman** [comment]
Does `--apple_generate_dsym` help?

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
