### ISSUE TITLE
A warning on Monterey

### ISSUE THREAD

**Issue by Seonny** [bazelbuild/tulsi#278]
Monterey says a warning during using tulsi.

<img width="603" alt="warning" src="https://user-images.githubusercontent.com/18515841/138013900-6199198f-bbcf-4f6c-a4d8-8d1bba47e400.png">

The Monterey version is 12.0.1 beta.

**Comment by DavidGoldman** [comment]
Tulsi will need to migrate to use Python 3 which should get rid of this warning

**Comment by giuk-jung** [comment]
It's a work-around. If you use git_repository() instead of http_archive(), the Warning popup will not appear.

**Comment by thii** [comment]
Resolved by https://github.com/bazelbuild/tulsi/commit/d3c7c715293c97dd016e268b1c90f36a8b11ef25.
