### ISSUE TITLE
Tulsi generated project showing .pcm not found warnings as errors 

### ISSUE THREAD

**Issue by CognitiveDisson** [bazelbuild/tulsi#279]
I still see this [issue (#135)](https://github.com/bazelbuild/tulsi/issues/135) with Xcode 13 and Xcode 12.4.
This behavior is observed only for the **legacy build system**.

I can reproduce this problem for my project using the master version of tulsi, Xcode 13 or Xcode 12. I have also checked that this behavior persists if I just `echo` this warning from the build phase script:
```
echo "warning: ./bazel-out/SomeTarget-AAAAAAAAAAAAA.pcm: No such file or directory"
```
This will be displayed as an error.

There was a [fix](https://github.com/bazelbuild/tulsi/pull/136) for this problem, but it was [reverted](https://github.com/bazelbuild/tulsi/pull/228). Can we get this fix back?

fyi @thii

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
