### ISSUE TITLE
Asset catalog files are rendered as Folders in generated project

### ISSUE THREAD

**Issue by rahul-malik** [bazelbuild/tulsi#28]
Issue: 
I'm generating a project for an ios_application target using tulsi that contains asset catalogs (*.xcassets). XCode has it's own viewer that it uses to display assets catalogs but tulsi's project generation renders these as folders.

From looking at the same project in XCode we have a difference in the project.pbxproj file:

Expected:
```
013B60D31A8403AB009E4376 /* Media.xcassets in Resources */ = {isa = PBXBuildFile; fileRef = 687E20E719958518005B84C3 /* Media.xcassets */; };
```

Actual:
```
966FB6DE564D875600000000 /* Media.xcassets */ = {
  isa = PBXGroup;
  children = (
    /* files here */
   );
   path = Media.xcassets;
   sourceTree = "<group>";
};
```

As you can see, XCode modifies it's project file to represent asset catalogs as `PBXBuildFile` objects vs `PBXGroup`. Resolving this should address the issue.

**Comment by DavidGoldman** [comment]
Hey! Could you attach a simple test project for us to reproduce this issue? Thanks
