### ISSUE TITLE
toolchain' does not contain a toolchain for cpu 'ios_sim_arm64'

### ISSUE THREAD

**Issue by alfian0** [bazelbuild/tulsi#282]
<img width="927" alt="Screen Shot 2021-11-17 at 08 38 17" src="https://user-images.githubusercontent.com/21122436/142093396-39feed3b-8b16-4cae-bd14-799a7c118894.png">

Is anyone get this error ? when run on simulator
Tulsi is generated and can run correctly with specific Bazel for specific project like Mediapipe use 3.7.2 and I try to use newer version to handle swift project but when I run on simulator got that error, this problem not found on MacBook Pro 2015 non Silicon Chip

One more, when I run with terminal with Mediapipe command on the doc this run successfully

Xcode 13.1 & 12.5.1
Bazel 4.2.1.1 & 3.7.2
MacBook Pro M1 chip

**Comment by thii** [comment]
You need Bazel 5.0+ to build for ios_sim_arm64 cpu.

**Comment by alfian0** [comment]
@thii thanks man, appreciate ...I use version 6.0.0 pre-release and worked
