### ISSUE TITLE
sh build_and_run.sh -x 13.1 error

### ISSUE THREAD

**Issue by XinlinLiu** [bazelbuild/tulsi#284]
tulsi git:(master) ✗ sh build_and_run.sh -x 13.1
ERROR: /Users/XXX/Desktop/tulsi/src/tools/bazel_cache_reader/BUILD:15:31: in macos_command_line_application rule //src/tools/bazel_cache_reader:bazel_cache_reader: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_XXXt/fb68c5d3e9c005e0f0ebc83ca5cddc9b/external/build_bazel_rules_apple/apple/internal/macos_rules.bzl", line 1192, column 58, in _macos_command_line_application_impl
		link_result = linking_support.register_linking_action(
	File "/private/var/tmp/_bazel_XXX/fb68c5d3e9c005e0f0ebc83ca5cddc9b/external/build_bazel_rules_apple/apple/internal/linking_support.bzl", line 103, column 47, in _register_linking_action
		return apple_common.link_multi_arch_binary(
Error in link_multi_arch_binary: link_multi_arch_binary() got unexpected keyword argument 'stamp'
ERROR: Analysis of target '//:tulsi' failed; build aborted: Analysis of target '//src/tools/bazel_cache_reader:bazel_cache_reader' failed
INFO: Elapsed time: 0.337s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets conf\
igured)

**Comment by keith** [comment]
You need a newer version of bazel. Which are you using now?

**Comment by XinlinLiu** [comment]
> 

3.7.2

**Comment by keith** [comment]
Can you test with 4.x

**Comment by XinlinLiu** [comment]
> Can you test with 4.x

4.2.1 Solved the above problem but other errors occurred.
![image](https://user-images.githubusercontent.com/15344356/144577550-99def346-96cc-4a5f-b96e-fa8dd4137eb8.png)

**Comment by thii** [comment]
> This usually means that the contents of a BUILD file are incorrect or flags are missing.

**Comment by XinlinLiu** [comment]
then downgrade to 3.7.2 the  error is resolved
