### ISSUE TITLE
"Jump to definition" not working between local swift modules

### ISSUE THREAD

**Issue by Ayatuas** [bazelbuild/tulsi#285]
Good afternoon!  

I try to use tulsi to generate my iOS project. There are several targets of "swift_library" and "objc_library" , including local targets and external packages. "Jump to definition" works fine in the following situations:
1.  from local swift modules to another modules generated by external packages;
2. from local swift modules to local objc modules;
But, "Jump to definition" not working between local swift modules like this:
![image](https://user-images.githubusercontent.com/28378181/144574548-0224a223-b2a0-46f3-b527-2401bc353d49.png)
![image](https://user-images.githubusercontent.com/28378181/144574627-56bbaded-406e-401a-b964-2fe164301079.png)
And "Show quick help" and code completion always work fine.

Why does this problem occur? And how can I solve it ?
Thank you!

**Comment by Ayatuas** [comment]
well, finally I found that there are only symlinks of `.swiftmodule` files in `bazel-tulsi-includes` , where swift import paths pointed to.  Actually Xcode cannot complete "Jump to definition" only with `.swiftmodule`.  So I change   `root_execution_path_fragment = symlink_path` to `root_execution_path_fragment = root_path` in `tulsi_aspects.bzl` . As a result, swift import paths are now configured correctly.

**Comment by vikage** [comment]
@Ayatuas I faced the same issue with you, I turned off legacy build system. It works for me
