### ISSUE TITLE
Bazel CI: Tulsi failing with both Bazel 4.2 and Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/tulsi#286]
https://buildkite.com/bazel/tulsi-bazel-darwin/builds/1665#_
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2273#22f5cb45-c21b-4f1f-931a-95bfadf2335b
```
Testing failed:
	BazelMacOSTests:
		The test runner encountered an error (Failed to establish communication with the test runner. If you believe this error represents a bug, please attach the result bundle at /Users/buildkite/Library/Developer/Xcode/DerivedData/temporary-gjggohogycdjgzdnuurieokkciir/Logs/Test/Test-Transient Testing-2021.12.06_00-16-41-+0000.xcresult. (Underlying Error: Couldnâ€™t communicate with a helper application. Try your operation again. If that fails, quit and relaunch the application and try again. The connection to service on pid 0 named com.apple.testmanagerd.control was invalidated.))

** TEST EXECUTE FAILED **
```

Please fix the build failures and in the meantime Tulsi will be disabled in Bazel downstream.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
