### ISSUE TITLE
sh commod errors

### ISSUE THREAD

**Issue by chengxiaoai** [bazelbuild/tulsi#288]
Skipping '//:tulsi': no such package '@rules_proto//proto': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_proto/archive/a0761ed101b939e19d83b2da5f59034bffc19c12.zip] to /private/var/tmp/_bazel_showcheng/bd7b7d4021486ebb04d29f5bb8dc2e79/external/rules_proto/temp1463343520883439093/a0761ed101b939e19d83b2da5f59034bffc19c12.zip: connect timed out

**Comment by thii** [comment]
Seems like something wrong with your network connection?

**Comment by afskalsfk** [comment]
Will VPN affect this? I encounter these problems with Chinese users

NFO: Repository build_bazel_rules_apple instantiated at:
  /Users//tulsi/WORKSPACE:18:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp//2ff2cd22c5d00ab843fed9a312f396f7/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://github.com/bazelbuild/rules_apple/releases/download/0.31.3/rules_apple.0.31.3.tar.gz failed: class java.io.IOException Proxy address 127.0.0.1:9999 is not a valid URL
ERROR: An error occurred during the fetch of repository 'build_bazel_rules_apple':
   Traceback (most recent call last):
	File "/private/var/tmp//2ff2cd22c5d00ab843fed9a312f396f7/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.31.3/rules_apple.0.31.3.tar.gz] to /private/var/tmp//2ff2cd22c5d00ab843fed9a312f396f7/external/build_bazel_rules_apple/temp6719171353214990428/rules_apple.0.31.3.tar.gz: Proxy address 127.0.0.1:9999 is not a valid URL
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/private/var/tmp//2ff2cd22c5d00ab843fed9a312f396f7/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.31.3/rules_apple.0.31.3.tar.gz] to /private/var/tmp//2ff2cd22c5d00ab843fed9a312f396f7/external/build_bazel_rules_apple/temp6719171353214990428/rules_apple.0.31.3.tar.gz: Proxy address 127.0.0.1:9999 is not a valid URL
ERROR: no such package '@build_bazel_rules_apple//apple': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.31.3/rules_apple.0.31.3.tar.gz] to /private/var/tmp//2ff2cd22c5d00ab843fed9a312f396f7/external/build_bazel_rules_apple/temp6719171353214990428/rules_apple.0.31.3.tar.gz: Proxy address 127.0.0.1:9999 is not a valid URL
INFO: Elapsed time: 12.826s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
(base)@yan

**Comment by thii** [comment]
```
Proxy address 127.0.0.1:9999 is not a valid URL
```

Are you setting that as a `--repo_env` flag? You may want to try using a valid URL (`http://127.0.0.1:9999`) instead.

**Comment by afskalsfk** [comment]
I don't know how to fix it now. I download the package and unzip it and then execute build_and_run.sh file

：：：：：：： sudo sh build_and_run.sh 

 An error occurred during the fetch of repository 'build_bazel_rules_apple':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_root/2ff2cd22c5d00ab843fed9a312f396f7/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_apple/releases/download/0.31.3/rules_apple.0.31.3.tar.gz] to /private/var/tmp/_bazel_root/2ff2cd22c5d00ab843fed9a312f396f7/external/build_bazel_rules_apple/temp15161330671814135599/rules_apple.0.31.3.tar.gz: Proxy address 127.0.0.1:9999 is not a valid URL

**Comment by afskalsfk** [comment]
I don't know how to fix it now. I download the package and unzip it and then execute build_and_run.sh file

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
