### ISSUE TITLE
Unable to build tulsi under mac os Big Sur 11.4

### ISSUE THREAD

**Issue by kaomoneus** [bazelbuild/tulsi#295]
Bazel version 4.2.1-homebrew

Steps to reproduce:
1. Get tulsi sources, I got commit 27981b25417
2. Change dir to sources root
3. `bash build_and_run.sh`

Result:
```
ERROR: /private/var/tmp/_bazel_stepan/960a4b0242d84c3b10d79bda8055c24e/external/build_bazel_rules_swift/swift/internal/compiling.bzl:737:17: 'lambda' not supported, declare a function instead
```

**Comment by wendyliga** [comment]
AFAIK you need to use bazel 5.0.0

**Comment by skofgar** [comment]
5.x and 6.x [seem to be pre-releases](https://github.com/bazelbuild/bazel/releases) at the moment? That's really unfortunate.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
