### ISSUE TITLE
errors when I run: sh build_and_run.sh

### ISSUE THREAD

**Issue by daver234** [bazelbuild/tulsi#296]
I have a MacBook Pro M1 Max using Xcode 13.2 and MacOS 12.1.  I get these errors when running the script.  Any suggestions for how to fix?  Thanks.

`Starting local Bazel server and connecting to it...
ERROR: /private/var/tmp/_bazel_daverothschild/bd470be6f9752c56a11a5ea82ad1a8f9/external/build_bazel_rules_swift/swift/internal/swift_clang_module_aspect.bzl:262:5: nested functions are not allowed. Move the function to the top level.
ERROR: Skipping '//:tulsi': error loading package '': in /private/var/tmp/_bazel_daverothschild/bd470be6f9752c56a11a5ea82ad1a8f9/external/build_bazel_rules_apple/apple/macos.bzl: in /private/var/tmp/_bazel_daverothschild/bd470be6f9752c56a11a5ea82ad1a8f9/external/build_bazel_rules_apple/apple/internal/testing/macos_rules.bzl: in /private/var/tmp/_bazel_daverothschild/bd470be6f9752c56a11a5ea82ad1a8f9/external/build_bazel_rules_apple/apple/internal/testing/apple_test_bundle_support.bzl: in /private/var/tmp/_bazel_daverothschild/bd470be6f9752c56a11a5ea82ad1a8f9/external/build_bazel_rules_swift/swift/swift.bzl: Extension 'swift/internal/swift_clang_module_aspect.bzl' has errors
WARNING: Target pattern parsing failed.
ERROR: error loading package '': in /private/var/tmp/_bazel_daverothschild/bd470be6f9752c56a11a5ea82ad1a8f9/external/build_bazel_rules_apple/apple/macos.bzl: in /private/var/tmp/_bazel_daverothschild/bd470be6f9752c56a11a5ea82ad1a8f9/external/build_bazel_rules_apple/apple/internal/testing/macos_rules.bzl: in /private/var/tmp/_bazel_daverothschild/bd470be6f9752c56a11a5ea82ad1a8f9/external/build_bazel_rules_apple/apple/internal/testing/apple_test_bundle_support.bzl: in /private/var/tmp/_bazel_daverothschild/bd470be6f9752c56a11a5ea82ad1a8f9/external/build_bazel_rules_swift/swift/swift.bzl: Extension 'swift/internal/swift_clang_module_aspect.bzl' has errors
INFO: Elapsed time: 2.258s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
    Fetching @bazel_skylib; fetching
    Fetching @rules_proto; fetching`

**Comment by keith** [comment]
You'll need a newer version of bazel, probably 5.x+, or an older version of rules_swift

**Comment by tanuuuu** [comment]
I have the same issue ,using Xcode version - 12.5.1 and bazel version - 4.2.2(installed through home-brew),Mac OS - Big Sur(version 11.5.1,macbook air chip - M1),How can I edit rule_swift ,is it file somewhere?

**Comment by daver234** [comment]
Thanks. How do I get a newer version?

**Comment by nouraraar20** [comment]
I've ran into same issue, and after trying many things, I've managed to run and generate the app
you have to open `WORKSPACE` file inside `tulsi-master` and replace the content to 

`load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
# TODO: Remove once https://github.com/bazelbuild/bazel-skylib/pull/307 is merged and patch is removed from rules_apple
http_archive(
    name = "io_bazel_stardoc",
    sha256 = "f89bda7b6b696c777b5cf0ba66c80d5aa97a6701977d43789a9aee319eef71e8",
    strip_prefix = "stardoc-d93ee5347e2d9c225ad315094507e018364d5a67",
    url = "https://github.com/bazelbuild/stardoc/archive/d93ee5347e2d9c225ad315094507e018364d5a67.tar.gz",
)

# TODO: Remove with next rules_swift + rules_apple release
git_repository(
    name = "build_bazel_rules_swift",
    remote = "https://github.com/bazelbuild/rules_swift.git",
    tag = "0.24.0",
)

git_repository(
    name = "build_bazel_rules_apple",
    remote = "https://github.com/bazelbuild/rules_apple.git",
    tag = "0.32.0",
)


load(
    "@build_bazel_rules_apple//apple:repositories.bzl",
    "apple_rules_dependencies",
)

apple_rules_dependencies()

# @build_bazel_rule_swift is already defined via apple_rules_dependencies above.
# This helps ensure that Tulsi, rules_apple, etc. are using the same versions.
load(
    "@build_bazel_rules_swift//swift:repositories.bzl",
    "swift_rules_dependencies",
)

swift_rules_dependencies()

# @build_bazel_apple_support is already defined via apple_rules_dependencies above.
# This helps ensure that Tulsi, rules_apple, etc. are using the same versions.
load(
    "@build_bazel_apple_support//lib:repositories.bzl",
    "apple_support_dependencies",
)

apple_support_dependencies()
`


and you have to make sure to clean the workspace every time you try something new

`bazel clean --expunge`

**Comment by daver234** [comment]
@nouraraar20 Wow, your suggestion worked.  Not sure how you figured all that out.  Thanks.  I did have to edit the script for Xcode 13.2 that I am using.  Hopefully, the main build instructions will be updated to support your suggestion.  Thanks!

**Comment by daver234** [comment]
@nouraraar20 Did you try to build MediaPipe?  I get a Bazel error: General failure: Bazel aspects could not be built.

**Comment by tanuuuu** [comment]
<img width="737" alt="Screenshot 2021-12-28 at 5 36 16 PM" src="https://user-images.githubusercontent.com/29446590/147564701-32a3b50b-e373-4297-a654-173c53e63d52.png">
@nouraraar20 thanks a lot it worked, tulsi was installed successfully but now I am not able to generate Xcode project for media pipe ,attaching screen shot

**Comment by daver234** [comment]
@tanuuuu Yes I have this same issue.  Please post any progress you make on solving this. Thanks.

**Comment by siyuyue** [comment]
@daver234 @tanuuuu I ran into the same issue and I went inside and deleted that --norun_validations option in src/TulsiGenerator/BazelAspectInfoExtractor.swift and rebuilt tulsi and now it starts working for me.

**Comment by nouraraar20** [comment]
@daver234 @tanuuuu glad to hear this worked for you, and thanks @siyuyue for helping solving this

**Comment by thii** [comment]
I added a fix in https://github.com/bazelbuild/tulsi/commit/3dd2bed8f02efed168f6f5233fb4dd17b62d5821 to make Tulsi be able to generate an Xcode project for projects that still use Bazel 4. Building Tulsi at HEAD still requires Bazel 5.0+. Until it gets an official release, you can do so with:

```
USE_BAZEL_VERSION=5.0.0rc3 sh build_and_run.sh -b `which bazelisk`
```

I have been able to generate an Xcode project for MediaPipe with this fix. Also, MediaPipe uses Bazel 4.2.1 which doesn't have support for the iOS simulator on M1, so you will need an Intel Mac to build it.

**Comment by daver234** [comment]
Ok the --noexperimental_run_validations change worked so I could generate the MediaPipe project.  But now I can't get things to build.  Did anyone else on this thread get iOS MediaPipe apps to build?  

Also, should I be running a new version of Bazel than 4.2.2?  I think the GitHub page has 4.2.2. the most current stable release.

Here is what I am seeing:
<img width="1287" alt="Screen Shot 2021-12-28 at 7 58 39 PM" src="https://user-images.githubusercontent.com/5413207/147626259-1ae66cdc-c410-4a32-9a1f-06e81a96d9ac.png">

**Comment by tanuuuu** [comment]
I have the same issue ,using Xcode version - 12.5.1 and bazel version - 4.2.2,Mac OS - Big Sur(version 11.5.1,macbook air chip - M1
<img width="1403" alt="Screenshot 2022-01-03 at 8 15 49 PM" src="https://user-images.githubusercontent.com/29446590/147944221-e655c8b1-d093-4679-983c-8213a3bd4287.png">
)
