### ISSUE TITLE
Projects generated with Tulsi fail to build

### ISSUE THREAD

**Issue by adamhowardprice** [bazelbuild/tulsi#3]
`--experimental_enable_objc_cc_deps` is a default option in projects generated by Tulsi. When I attempt to build the Xcodeproj it generates, it fails with the error "No toolchain found for cpu 'watchos_i386'" This issue appears to be the same as is written up [here](https://groups.google.com/forum/#!topic/tulsi-discuss/An-de9qRXYo).

For now, it is possible to pass in `--noexperimental_enable_objc_cc_deps` as a workaround, but that won't be possible when generating a workspace where we need ObjC libraries to depend on cc_libraries.

**Comment by adamhowardprice** [comment]
@abaire I spoke with Peter Schmitt about this recently, and he mentioned it was an unintended consequence of something else in Bazel. I'll duplicate this issue in Bazel just in case.

**Comment by abaire** [comment]
@kelvinchan-google (new maintainer of Tulsi)

**Comment by robbiexperiel** [comment]
@kelvinchan-google do you have any information/updates about this bug? I'm running into the same issue, and unfortunately --noexperimental_enable_objc_cc_deps isn't an option for us.

**Comment by aragos** [comment]
Another way to work around this issue is to add (real or empty) toolchains to your CROSSTOOL with the names required by the logic. We're planning to add auto-generation for those toolchains soon: bazelbuild/bazel#1279

**Comment by kelvinchan-google** [comment]
@robbiexperiel, can you try the workaround that @aragos as suggested? Unfortunately we won't be able to prioritize any short term fixes and are relying on the auto-generation that @aragos is referring to as the proper/long-term solution.

**Comment by robbiexperiel** [comment]
Thanks for the tip @aragos! I tried making a custom CROSSTOOL for watchos_i386, but it doesn't seem to be working. I've never dealt with CROSSTOOL configs before, so I'm probably doing something dumb.

Here is the configuration I made: https://gist.github.com/robbiexperiel/74b57ac791bd42b047bbe6d432fcac35
The following command is the command that Tulsi invokes, but with the --crosstool_top flag added in:
> bazel build --experimental_enable_objc_cc_deps --verbose_failures --config=ios_arm64 --config=ios-device --compilation_mode=dbg --xcode_version=8.2.1 --ios_sdk_version=10.2 --crosstool_top=tools/ios //some:IosApplication
ERROR: No toolchain found for cpu 'darwin'. Valid cpus are: [
  watchos_i386,
].

When I run the same thing, but with a "darwin" toolchain defined along with the watchos_i386 one, I get the following error, which seems to imply it's using the default CROSSTOOL config:
ERROR: No toolchain found for --cpu='watchos_i386' --compiler='compiler'. Valid toolchains are: [
  --cpu='armeabi-v7a' --compiler='compiler' --glibc='armeabi-v7a',
  --cpu='ios_x86_64' --compiler='compiler' --glibc='ios',
  --cpu='darwin' --compiler='compiler' --glibc='macosx',
  --cpu='x64_windows_msvc' --compiler='cl' --glibc='msvcrt140',
].

It seems as though bazel doesn't fall back to the default CROSSTOOL config if the custom one doesn't have the desired configuration. Is that correct and intended? If so, does that mean I'll need to copy the configs out of the bazel repository and modify them?

**Comment by aragos** [comment]
Apple rules use a different crosstool from the one set by `--crosstool_top` (sorry, should have mentioned that!). Use `--apple_crosstool_top` to pass the crosstool with the iOS and watch toolchains that you need, that should do the right thing.

(Apple rules are objc_*, ios_* and their dependencies. So cc_libraries are affected by `--crosstool_top` normally but by `--apple_crosstool_top` if in the dependency closure of an objc_* target).

**Comment by robbiexperiel** [comment]
Thanks, using `--apple_crosstool_top`, and defining ios_x86_64 and tvos_x86_64 fixed things!

**Comment by lswith** [comment]
can we get this fixed in the latest version of Tulsi? seems like its a solved problem now.

**Comment by dflems** [comment]
The latest version of Tulsi seems to no longer set this flag (it's a bazel default, but can be overridden on the command line)

**Comment by dmishe** [comment]
That's right, you should not need to provide your own crosstool anymore, Bazel will generate one. I am going to close this issue.
