### ISSUE TITLE
XCTAssertFailure message does not pin on source code

### ISSUE THREAD

**Issue by wendyliga** [bazelbuild/tulsi#303]
when testing ios_unit_test on Xcode and some test cases are failed, the message doesn't pin on source code.
is it a known issue?

![Screen Shot 2022-02-03 at 13 56 42](https://user-images.githubusercontent.com/16457495/152295827-4cede73a-0bcd-4865-bf1d-4a8f84701d93.png)

this is the example repo https://github.com/wendyliga/simple_bazel.

**Comment by keith** [comment]
We use this workaround for this https://www.smileykeith.com/2021/03/04/supporting-relative-paths/

**Comment by wendyliga** [comment]
@keith thanks for the response and such an elaborate blog post.
this solution should fix the issue.

regarding using `NSPrincipalClass`, did you manage to get one working for ios unit test?

**Comment by keith** [comment]
Yes, you just have to add it to the plist for your test bundle like normal, you might not be passing `infoplists` so you'll have to add one if so

**Comment by keith** [comment]
you'll have to use the module name from the target, which may not match the target's name directly

**Comment by wendyliga** [comment]
got it, on my case, it should use this PRODUCT_MODULE_NAME to work

thanks again @keith 
![Screen Shot 2022-02-04 at 01 19 24](https://user-images.githubusercontent.com/16457495/152404353-cf4ba2d7-b8db-48c8-9de1-4051dab0792b.png)
