### ISSUE TITLE
Tulsi doesn't generate an xcassets catalog for `app_icons` parameter of `ios_application` rule

### ISSUE THREAD

**Issue by shamanskyh** [bazelbuild/tulsi#31]
Hi, I have an `ios_application` rule from the [rules_apple](https://github.com/bazelbuild/rules_apple) repo in my BUILD file. It uses the `app_icons` parameter to supply an .xcassets catalog with the app icons. We don't change these very frequently, but it'd be ideal if Tulsi could make the .xcassets catalog available in the project that's generated.

**Comment by shamanskyh** [comment]
cc @timonus

**Comment by timonus** [comment]
+1

**Comment by DavidGoldman** [comment]
Hey,

Is it not showing up in the project at all? Could you provide us with a simple test project so we can reproduce?

Thanks

**Comment by shamanskyh** [comment]
Thanks for getting back to me @DavidGoldman. After creating a sample project to try to demo what I'm seeing, I find that I'm unable to reproduce the issue on Tulsi master. I think our internal version is slightly behind, so that could be the cause. Thanks for taking a quick look into this, and sorry that I didn't confirm the issue before filing!

@timonus, I'll make sure we make the necessary changes here to get the app icon catalog in the generated project.

**Comment by DavidGoldman** [comment]
No problem. For your reference, It's likely that either 039bfbb and/or 2a7152d fixed this issue.
