### ISSUE TITLE
Test targets do not index if they rely on imported dynamic frameworks

### ISSUE THREAD

**Issue by erikkerber** [bazelbuild/tulsi#315]
During project generation, Tulsi purposely skips creating index targets for tests, [because it believes it makes proper targets for tests](https://github.com/bazelbuild/tulsi/blob/master/src%2FTulsiGenerator%2FPBXTargetGenerator.swift#L591)

If a test depends on a packaged dynamic `.framework`, however, the test target does not get its `FRAMEWORK_SEARCH_PATH` updated with the location of those frameworks. When creating an index target, the build graph is [recursively traversed to find and populate these](https://github.com/bazelbuild/tulsi/blob/master/src%2FTulsiGenerator%2FPBXTargetGenerator.swift#L572-L576), which is not done for non-index targets.

Though I'm confident this is a bug, I'd love to solicit feedback on if the answer is to:

1. Simply make index targets for tests as well
2. Recursively traverse dependencies to populate search paths for non-index targets.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
