### ISSUE TITLE
Xcode Code Coverage

### ISSUE THREAD

**Issue by wendyliga** [bazelbuild/tulsi#327]
seems now, based on the latest rules_apple, there's an improvement to add code coverage to `ios_unit_test` https://github.com/bazelbuild/rules_apple/pull/1223

is there any plan to make it compatible with Xcode code coverage reading?

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
