### ISSUE TITLE
MediaPipe-0.8.9 using tulsi to generate xcode project failed

### ISSUE THREAD

**Issue by LostPeter** [bazelbuild/tulsi#329]
bazel's version 5.1.0
bazel's examples use tulsi to generate  ios-app xcode project success and can run

![image](https://user-images.githubusercontent.com/17842877/163118021-90f8ddf5-0de0-49ad-8c71-3fde29d7ba45.png)
![image](https://user-images.githubusercontent.com/17842877/163118078-7782653c-8103-4e93-827e-bf200344f2f8.png)
![image](https://user-images.githubusercontent.com/17842877/163118065-07815212-6382-4b0f-8d2f-1161d6230de4.png)

**Comment by wenoptics** [comment]
I solve this issue by install `bazel==5.2.0` as mediapipe currently requires the [exact version](https://github.com/google/mediapipe/blob/1fb0902aa06d45ebc73f5337d9f65f06c418c24b/.bazelversion).

Also, I got more explicit error messages when copy and paste the failed `bazel info <...>` command - Maybe an improvement for Tulsi to report errors from stdout/stdout here

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
