### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by veolata** [bazelbuild/tulsi#330]
Sorry to bother, I'm in China, don't know if this error due to the network connection.
run the shell many times, seems it gives the counter down, 1st paragraph
then suddenly failed  , 2nd paragraph

dl@bogon tulsi % sh build_and_run.sh
INFO: Analyzed target //:tulsi (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[3 / 25] 8 actions running
    StoryboardCompile tulsi-intermediates/Base.lproj_storyboardc/Main.storyboardc; 5s local
    XibCompile tulsi-intermediates/nibs/Base.lproj/NewGeneratorConfigViewController; 5s local
    XibCompile tulsi-intermediates/nibs/Base.lproj/ErrorAlertDetailView; 5s local
    XibCompile tulsi-intermediates/nibs/Base.lproj/NewProjectViewController; 5s local
    Compiling Swift module //src/TulsiGenerator:tulsi_generator_lib; 5s local
    XibCompile tulsi-intermediates/nibs/Base.lproj/SplashScreenWindowController; 5s local
    Compiling Swift module //src/tools/module_cache_pruner:module_cache_pruner_lib; 5s local
    XibCompile tulsi-intermediates/nibs/Base.lproj/XcodeProjectGenerationProgressViewController; 5s local

dl@bogon tulsi % sh build_and_run.sh
INFO: Analyzed target //:tulsi (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/dl/Desktop/mediapipe/tulsi/BUILD:61:18: XibCompile tulsi-intermediates/nibs/Base.lproj/SplashScreenWindowController failed: (Exit 255): xctoolrunner failed: error executing command bazel-out/darwin-opt-exec-2B5CBBC6-ST-ee81979272f8/bin/external/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner ibtool --compile ... (remaining 8 arguments skipped)
dyld: lazy symbol binding failed: can't resolve symbol _$s19CoreDeviceProtocols0B5StateOMa in /Applications/Xcode.app/Contents/Developer/usr/bin/../../../SharedFrameworks/DVTFoundation.framework/Versions/A/DVTFoundation because dependent dylib /Library/Developer/PrivateFrameworks/CoreDevice.framework/Versions/A/CoreDevice could not be loaded
dyld: can't resolve symbol _$s19CoreDeviceProtocols0B5StateOMa in /Applications/Xcode.app/Contents/Developer/usr/bin/../../../SharedFrameworks/DVTFoundation.framework/Versions/A/DVTFoundation because dependent dylib /Library/Developer/PrivateFrameworks/CoreDevice.framework/Versions/A/CoreDevice could not be loaded
ERROR: /Users/dl/Desktop/mediapipe/tulsi/BUILD:61:18: XibCompile tulsi-intermediates/nibs/Base.lproj/NewProjectViewController failed: (Exit 255): xctoolrunner failed: error executing command bazel-out/darwin-opt-exec-2B5CBBC6-ST-ee81979272f8/bin/external/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner ibtool --compile ... (remaining 8 arguments skipped)
dyld: lazy symbol binding failed: can't resolve symbol _$s19CoreDeviceProtocols0B5StateOMa in /Applications/Xcode.app/Contents/Developer/usr/bin/../../../SharedFrameworks/DVTFoundation.framework/Versions/A/DVTFoundation because dependent dylib /Library/Developer/PrivateFrameworks/CoreDevice.framework/Versions/A/CoreDevice could not be loaded
dyld: can't resolve symbol _$s19CoreDeviceProtocols0B5StateOMa in /Applications/Xcode.app/Contents/Developer/usr/bin/../../../SharedFrameworks/DVTFoundation.framework/Versions/A/DVTFoundation because dependent dylib /Library/Developer/PrivateFrameworks/CoreDevice.framework/Versions/A/CoreDevice could not be loaded
Target //:tulsi failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.886s, Critical Path: 6.71s
INFO: 9 processes: 9 internal.
FAILED: Build did NOT complete successfully

is there any other way to build and setup tulsi, like bazel using brew?

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
