### ISSUE TITLE
How to get back from Bazel and tulsi?

### ISSUE THREAD

**Issue by CharlotteFallices** [bazelbuild/tulsi#335]
I'm sorry for that but they're making our new members have some trouble getting involved with the project, so we're going to switch to a more general approach, is there any way we can do this quickly?

**Comment by keith** [comment]
Are you asking if there's an easy way to convert from a bazel based build back to an Xcode based build? If so I don't know of any tools to help do this as it likely hasn't happened many times.

**Comment by wendyliga** [comment]
you could use [xcodegen](https://github.com/yonaskolb/XcodeGen), it uses yml to define the necessary info to generate xcodeproj, same as BUILD.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
