### ISSUE TITLE
python3 errno=No such file or directory

### ISSUE THREAD

**Issue by lovelycheep** [bazelbuild/tulsi#341]
➜  tulsi git:(master) ✗ sh build_and_run.sh
INFO: Build option --macos_cpus has changed, discarding analysis cache.
INFO: Analyzed target //:tulsi (0 packages loaded, 1203 targets configured).
INFO: Found 1 target...
ERROR: /Users/yangyx/work/tulsi/BUILD:61:18: XibCompile tulsi-intermediates/nibs/Base.lproj/XcodeProjectGenerationProgressViewController failed: (Exit 71): xctoolrunner failed: error executing command bazel-out/darwin-opt-exec-2B5CBBC6-ST-83c7a2d338b1/bin/external/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner ibtool --compile ... (remaining 8 arguments skipped)
python3: error: can't exec '/Applications/Xcode.app/Contents/Developer/usr/bin/python3' (errno=No such file or directory)
Target //:tulsi failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.374s, Critical Path: 3.20s
INFO: 62 processes: 49 internal, 13 darwin-sandbox.
FAILED: Build did NOT complete successfully

can any one help me for the mac m1 problem?

**Comment by keith** [comment]
What version of Xcode are you using?  Do you not have a `python3` executable there? `'/Applications/Xcode.app/Contents/Developer/usr/bin/python3` Have you opened Xcode and accepted the license agreements? Make sure `xcode-select -p` shows the correct path to your Xcode installation, otherwise you'll need to set that with `xcode-select -s`

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
