### ISSUE TITLE
Unsupported target type: macos_application (target //examples/macos/HelloWorldSwift:HelloWorldSwift)

### ISSUE THREAD

**Issue by andy380743909** [bazelbuild/tulsi#343]
I use tulsi to generate xcode project for mediapipe macOS example app, but it failed with this error.
![Snip20220706_2](https://user-images.githubusercontent.com/1617427/177531261-c1e18d1e-0719-4461-8fb5-84ab65a05d8d.png)
![Snip20220706_3](https://user-images.githubusercontent.com/1617427/177531293-fa652210-9d40-4f87-b932-9ef9104b5028.png)
![Snip20220706_4](https://user-images.githubusercontent.com/1617427/177531333-249ee2dc-901e-49a0-83d2-28909458a4c7.png)

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
