### ISSUE TITLE
apple_framework is support ?

### ISSUE THREAD

**Issue by hzfanfei** [bazelbuild/tulsi#345]
When I use apple_framework, tulsi generate xcode project is error.

**Comment by keith** [comment]
If that is a rule from rules_ios I imagine it would require some changes to support

**Comment by Jacky-LinPeng** [comment]
I meet the same problem
`n @tulsi//:tulsi/tulsi_aspects.bzl%tulsi_outputs_aspect aspect on apple_framework_packaging rule //Pods/Alamofire:Alamofire: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_mac/bc1c6640115027b0e8599f0594bf3ae0/external/tulsi/tulsi/tulsi_aspects.bzl", line 1135, column 39, in _tulsi_outputs_aspect
		artifact = bundle_info.archive.path
Error: 'NoneType' value has no field or method 'path'
error: Analysis of aspects '[@tulsi//:tulsi/tulsi_aspects.bzl%tulsi_outputs_aspect] on //:NewsApplication' failed; build aborted: Analysis of target '//Pods/Alamofire:Alamofire' failed
note: Elapsed time: 0.222s
note: 0 processes.
error: Build did NOT complete successfully (1 packages loaded, 97 targets configured)
<*> Running Bazel completed in 312.916 ms
/Users/mac/Documents/xunlei/FORK/ios-bazel-example/App.xcodeproj/.tulsi/Scripts/bazel_build.py:590: error: Bazel build failed with exit code 1. Please check the build log in Report Navigator (⌘9) for more information.
<*> Everything completed in 329.497 ms
`

**Comment by Jacky-LinPeng** [comment]
but bazel build ://xx  
success!!!!

**Comment by Jacky-LinPeng** [comment]
> If that is a rule from rules_ios I imagine it would require some changes to support
Yeah, using rules_ios apple_framework,
However, the Xcode compiler failed to compile, but bazel build can compile properly, do you have any suggestions

**Comment by Jacky-LinPeng** [comment]
> If that is a rule from rules_ios I imagine it would require some changes to support

Yeah, using rules_ios apple_framework,
However, the Xcode compiler failed to compile, but bazel build can compile properly, do you have any suggestions

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
