### ISSUE TITLE
Consider removing the hardcoded `--strip=always`

### ISSUE THREAD

**Issue by kkpattern** [bazelbuild/tulsi#352]
Currently, Tulsi [hardcoded a `--strip=always` flag in release mode](https://github.com/bazelbuild/tulsi/blob/c7609aa3914123f1b5f1a6b5caff551617a325c9/src/TulsiGenerator/BazelSettingsProvider.swift#L137). This makes us unable to debug a release build in XCode. But sometimes, we need to debug a release build. For example, the debug build may be too slow for some projects. Or sometimes, the debug build and release build behavior differently, and we want to find out why.

Apple platform actually has good support for release debug. The debug symbols are stored in dSYM(if configured this way), so the release binary can stay small.

We tried removing the `--strip=always` flag from the Tulsi source and debugging in release mode works. I think we can consider removing the hardcoded `--strip=always`. If users need this flag, they can always add it in the tulsiproject config.

**Comment by keith** [comment]
The assumption is definitely that you shouldn't be using tulsi for building the release configuration unless you're using it to release, but I now understand from the other issue why you're doing that. Adding a way to override the default flags for release mode would probably be fine.

**Comment by thii** [comment]
@kkpattern Feel free to send a PR to remove it.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
