### ISSUE TITLE
Creating symlink bazel-out/applebin_ios-ios_arm64-dbg-ST-2967bd56a867/bin/mediapipe/examples/ios/handdetectiongpu/HandDetectionGpuApp-intermediates/embedded.mobileprovision failed: missing input file '//mediapipe:provisioning_profile.mobileprovision'

### ISSUE THREAD

**Issue by AmanToshniwal** [bazelbuild/tulsi#356]
I am trying to run Mediapipe hand detection on my iPad, but after all the steps have been completed successfully, at the final step when I build the app the below errors come up.

note: Found 1 target...
[0 / 4] [Prepa] BazelWorkspaceStatusAction stable-status.txt
/Users/amantoshniwal/mediapipe/mediapipe/examples/ios/handdetectiongpu/BUILD:34:16: error: Creating symlink bazel-out/applebin_ios-ios_arm64-dbg-ST-2967bd56a867/bin/mediapipe/examples/ios/handdetectiongpu/HandDetectionGpuApp-intermediates/embedded.mobileprovision failed: missing input file '//mediapipe:provisioning_profile.mobileprovision'
/Users/amantoshniwal/mediapipe/mediapipe/examples/ios/handdetectiongpu/BUILD:34:16: error: Creating symlink bazel-out/applebin_ios-ios_arm64-dbg-ST-2967bd56a867/bin/mediapipe/examples/ios/handdetectiongpu/HandDetectionGpuApp-intermediates/embedded.mobileprovision failed: 1 input file(s) do not exist
Aspect @tulsi//:tulsi/tulsi_aspects.bzl%tulsi_outputs_aspect of //mediapipe/examples/ios/handdetectiongpu:HandDetectionGpuApp up-to-date:
  bazel-out/applebin_ios-ios_arm64-dbg-ST-2967bd56a867/bin/mediapipe/examples/ios/handdetectiongpu/HandDetectionGpuApp.tulsiouts
error: /Users/amantoshniwal/mediapipe/mediapipe/examples/ios/handdetectiongpu/BUILD:34:16 Creating symlink bazel-out/applebin_ios-ios_arm64-dbg-ST-2967bd56a867/bin/mediapipe/examples/ios/handdetectiongpu/HandDetectionGpuApp-intermediates/embedded.mobileprovision failed: 1 input file(s) do not exist
note: Elapsed time: 1.399s, Critical Path: 0.00s
note: 2 processes: 2 internal.
error: Build did NOT complete successfully
<*> Running Bazel completed in 1548.087 ms
/Users/amantoshniwal/Desktop/Mediapipe.xcodeproj/.tulsi/Scripts/bazel_build.py:591: error: Bazel build failed with exit code 1. Please check the build log in Report Navigator (⌘9) for more information.
<*> Everything completed in 1565.651 ms

Also , when I run the below command on terminal , it shows build completed successfully but no, Bazel .ipa file is being created.

command:  bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp

Any help regarding this will be appreciated.

**Comment by AmanToshniwal** [comment]
I have updated tulsi for my Xcode version of 13.3.1 , any changes that you may suggest.
Or should I just wait for iOS 16 release.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
