### ISSUE TITLE
Unit Test with Xcode 14 seems stuck

### ISSUE THREAD

**Issue by wendyliga** [bazelbuild/tulsi#358]
![SCR-20220921-c41](https://user-images.githubusercontent.com/16457495/191395395-c238130c-c51f-48d7-a948-5122b990892a.png)

# Description
Xcode 14 removes legacy build. this is likely the cause of this behavior.

# How to reproduce
- project: https://github.com/wendyliga/simple_bazel
- open `simple_bazel.tulsiproj` and generate `application`
- run test on xcode 14

**Comment by thii** [comment]
Should be fixed by https://github.com/bazelbuild/tulsi/commit/dd35a9e53de18b3f266a41730e5b023a5a514ec4.
