### ISSUE TITLE
macos_unit_test build error; failed to extract Authority

### ISSUE THREAD

**Issue by benvanik** [bazelbuild/tulsi#36]
I'm trying to use the latest bazel MacOS rules and running into issues.
The first one is the following error produced during builds in Xcode:

```
:: error: Failed to extract Authority from Executable=/Users/benvanik/Library/Developer/Xcode/DerivedData/xrtl-cjlbibwnoyhiwycwlchzxhjarjqp/Build/Products/__TulsiTestRunner_Debug/arena_test_macos_xctest.xctest/Contents/MacOS/arena_test_macos_xctest
```

The binary does not have 'Authority':
```
codesign -dv --verbose=4 /Users/benvanik/Library/Developer/Xcode/DerivedData/xrtl-cjlbibwnoyhiwycwlchzxhjarjqp/Build/Products/__TulsiTestRunner_Debug/arena_test_macos_xctest.xctest/Contents/MacOS/arena_test_macos_xctest
Executable=/Users/benvanik/Library/Developer/Xcode/DerivedData/xrtl-cjlbibwnoyhiwycwlchzxhjarjqp/Build/Products/__TulsiTestRunner_Debug/arena_test_macos_xctest.xctest/Contents/MacOS/arena_test_macos_xctest
Identifier=com.xrtl.foo
Format=bundle with Mach-O thin (x86_64)
CodeDirectory v=20100 size=4381 flags=0x2(adhoc) hashes=132+3 location=embedded
OSPlatform=36
OSSDKVersion=658432
OSVersionMin=658432
Hash type=sha256 size=32
CandidateCDHash sha256=42c3ee4af649f8c8e3da2c4fb69b67be52c6dc09
Hash choices=sha256
Page size=4096
CDHash=42c3ee4af649f8c8e3da2c4fb69b67be52c6dc09
Signature=adhoc
Info.plist entries=15
TeamIdentifier=not set
Sealed Resources version=2 rules=13 files=0
Internal requirements count=0 size=12
```

This is produced with a check in Tulsi here:
https://github.com/bazelbuild/tulsi/blob/706bacb4999458a9aa3e0b755893f355fda3ebea/src/TulsiGenerator/Scripts/bazel_build.py#L108

If I add this fallback when it's trying to print the error the build succeeds and the test runs:
```
        self.attributes[attribute] = '-'
```

I'm not sure the root cause or reason why the Authority expectation exists. Would such a fallback for missing Authority be acceptable for a PR?

**Comment by StevenEWright** [comment]
I believe https://github.com/bazelbuild/tulsi/commit/fc11ea3330b9d8a07bdd33d0b4af48124a5f90e2 has addressed this specific issue, and we can close this.

**Comment by nglevin** [comment]
But let us know if you still have this problem!
