### ISSUE TITLE
I can't compile the sh file successfully

### ISSUE THREAD

**Issue by asd26187** [bazelbuild/tulsi#360]
sh build_and_run.sh 
ERROR: /private/var/tmp/_bazel_yunxiao/f105df080db21e26596eada1510c89c8/external/local_config_xcode/BUILD:12:13: in xcode_config rule @local_config_xcode//:host_xcodes: --xcode_version=13.2.1 specified, but '13.2.1' is not an available Xcode version. available versions: [13.4.1.13F100]. If you believe you have '13.2.1' installed, try running "bazel shutdown", and then re-run your command.

cat .bazelrc
-- https://github.com/bazelbuild/stardoc/issues/112
common --incompatible_allow_tags_propagation

build --cpu=darwin_x86_64
build --apple_platform_type=macos

-- This is required for re-invoking bazel in shell tests. CI adds it implicitly
test --test_env=HOME

I found no xcode version restriction code，What should I do next?

**Comment by thii** [comment]
You can change the Xcode version Tulsi should be built for with `-x`:
```
sh build_and_run.sh -x 13.4.1
```

**Comment by asd26187** [comment]
Yes, following your approach has successfully solved my problem, thks!
