### ISSUE TITLE
Crash on macOS13.0.1 And Xcode14

### ISSUE THREAD

**Issue by WorldObserver-cli** [bazelbuild/tulsi#392]
env: 

macOS 13.0.1 
Xcode 14
bazel 5.2.0

I built tulsi app using buid_and_run.sh and have generated tulsi app in mac Applications. 
But when I open tulsi app, it crashes on my mac.

Does anyone have same issue?

**Comment by sergiocasaspastor** [comment]
Yes, same issue here. I couldn't open tulsi after building it

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
