### ISSUE TITLE
Xcode project build

### ISSUE THREAD

**Issue by mademao** [bazelbuild/tulsi#394]
<img width="1698" alt="image" src="https://user-images.githubusercontent.com/18652191/209542615-d4de0ee6-5c7b-434b-96ef-a82446950f90.png">

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
