### ISSUE TITLE
Tulsi does not work when experimental_local_disk_cache is used

### ISSUE THREAD

**Issue by mikelikespie** [bazelbuild/tulsi#40]
It doesn't find the tulsiinfo files. This is because the event logs look like

```
            {
                "name": "external/bazel_j2objc/jre_security_lib.tulsiinfo",
                "uri": "bytestream://null/blobs/d52a2a73180de9a81631b96cdf51613ad96a6464/292"
            },
```

with the bytestream uri, instead of a file:// URI

This is using master of bazel @ `210cdeb8a7836c5fd586a29d73c8013f325d3883`

I think it will reproduce on any project if `--experimental_local_disk_cache` and `--experimental_local_disk_cache_path` are used.

**Comment by DavidGoldman** [comment]
Thanks for reporting.

This is an interesting problem, is there a valid URI to the files anywhere in the build log? Without a valid URI pointing to the files I'm not sure what we can do on Tulsi's end to fix this.

**Comment by mikelikespie** [comment]
nice! Thanks @bazel-io
