### ISSUE TITLE
BUILD files are added even when using BUILD.bazel files

### ISSUE THREAD

**Issue by DavidGoldman** [bazelbuild/tulsi#44]
See https://github.com/dflems/bazel-repro/tree/master/tulsi-local-repo for an example project.

When using `BUILD.bazel` files (i.e. `package/BUILD.bazel`), Tulsi adds both `package/BUILD` and `package/BUILD.bazel` as file references in the Xcodeproj even though only the `BUILD.bazel` file exists.

**Comment by DavidGoldman** [comment]
Taking a quick look into this, we forcibly add a `BUILD` file reference for every package in your project when you create it. We can probably remove this altogether or check for file existence before we add it.

See the relevant [UI code](https://github.com/bazelbuild/tulsi/blob/5da6358b14fdf87ccbe2fc3671c89b91cfd3afd5/src/Tulsi/ProjectEditorConfigManagerViewController.swift#L151) and [CLI code](https://github.com/bazelbuild/tulsi/blob/5da6358b14fdf87ccbe2fc3671c89b91cfd3afd5/src/Tulsi/HeadlessTulsiProjectCreator.swift#L172).

**Comment by ravimandala** [comment]
@DavidGoldman I am sure you might have figured this out, but for everyone's reference -- one workaround for this issue is...
1. Open `.tulsigen` file(s) under `Configs` directory in the Tulsi project.
1. Rename files from `BUILD` to `BUILD.bazel` in `additionalFilePaths` section.
1. And then generate the Xcode project from GUI or CLI.

**Comment by DavidGoldman** [comment]
As an alternative workaround you can modify the two codepaths I listed above and replace"BUILD" with "BUILD.bazel" or perhaps this could be some Tulsi config setting.

**Comment by ravimandala** [comment]
Tulsi needs to support the use of either `BUILD` or `BUILD.bazel`, so it's more than replacing `BUILD` with `BUILD.bazel`.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
