### ISSUE TITLE
Tulsi does not add srcs for genrules to Xcode project

### ISSUE THREAD

**Issue by jbeder** [bazelbuild/tulsi#47]
Here's a small example, with a dummy genrule that just copies a file to be used as a header:

BUILD:

```py
genrule(
    name = "dep",
    srcs = ["dep.in"],
    outs = ["dep.h"],
    cmd = "cp $(location dep.in) $@",
)

cc_binary(
    name = "main",
    srcs = [
        "main.cc",
        ":dep",
    ],
)
```

dep.in

```h
inline int foo() { return 42; }
```

main.cc

```cc
#include "test/dep.h"
#include <iostream>

int main() {
  std::cout << foo() << "\n";
  return 0;
}
```

When I run Tulsi with this BUILD file, I want the file `dep.in` included in my Xcode project. (Reason: it's the source file, so I want to be able to edit it in Xcode and then recompile.)

Instead, the most I can see (if I select absolutely everything when generating the project) is the generated `test/dep.h`.

**Comment by DavidGoldman** [comment]
Currently we don't create any indexer targets for genrules; do you just want the file reference to be present in the Xcode project but not bound to any particular target?

**Comment by jbeder** [comment]
Right; I just want it there so I can edit it in Xcode and recompile.

**Comment by DavidGoldman** [comment]
This should be fixed as of 3476863.

**Comment by StevenEWright** [comment]
@DavidGoldman do we want to reopen?

**Comment by DavidGoldman** [comment]
@StevenEWright Thanks. While 3476863 fixed this, it may cause errors when building your application in a Tulsi-generated xcodeproj. abc1ac29 contains the proper fixes to get this working properly.
