### ISSUE TITLE
cannot make generator configs done

### ISSUE THREAD

**Issue by DinnerHowe** [bazelbuild/tulsi#48]
hi all 

I was stoped by step: 4. Create project generator configs ~ step: The Tulsi generator configuration editor in this tutorial: https://tulsi.bazel.build/docs/gettingstarted.html

in the tutorial, it said "Clicking the "+" button will allow you to add new generator configs. Double clicking on an existing config will allow you to edit it, and the "-" button can be used to permanently delete previously created configs."

however when I Clicked the "+" button, it came out this:

<img width="721" alt="2018-04-07 20 45 43" src="https://user-images.githubusercontent.com/13310627/38455052-d0194152-3aa4-11e8-9ea2-6caa9df32510.png">

I so confuse about how can I do after this window came out?

thanks advance

**Comment by dierksen** [comment]
This should hopefully be less of an issue as of https://github.com/bazelbuild/tulsi/commit/799fa543f8e2c68b32dc46081b83719428ee8203 . As long as you have `bazel` on your PATH, it should be selected automatically.
