### ISSUE TITLE
Support easily using the Homebrew version of bazel

### ISSUE THREAD

**Issue by jfaust** [bazelbuild/tulsi#49]
The official Bazel installation instructions recommend using Homebrew: https://docs.bazel.build/versions/master/install-os-x.html

Using this version of bazel in Tulsi is unintuitive, since it's in `/usr/local/bin` and the standard Finder open dialog requires you to use `Cmd+Shift+G` to open that directory.

Recommendation: auto-detect `bazel` versions in `PATH` and use those by default?

**Comment by dierksen** [comment]
Fixed in https://github.com/bazelbuild/tulsi/commit/799fa543f8e2c68b32dc46081b83719428ee8203 .
