### ISSUE TITLE
Tulsi will complain if it finds `bazel-` annywhere in the path to the project

### ISSUE THREAD

**Issue by fstephany** [bazelbuild/tulsi#51]
Tulsi will complain if you have `bazel-` anywhere in the path. Should'nt be the check scoped to the directory where the `WORKSPACE` file resides?

In this screenshot, my project is in a directory called `bazel-blog-post`.

<img width="835" alt="tulsi-bazel-prefix" src="https://user-images.githubusercontent.com/35817/42104696-df1ad2aa-7bcd-11e8-944e-6ae450ea3a8a.png">

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
