### ISSUE TITLE
Support for header search path defined in COPTS

### ISSUE THREAD

**Issue by xinzhengzhang** [bazelbuild/tulsi#57]
Tulsi only transfer the includes header defines in `include` label  into `HEADER_SEARCH_PATHS`
Mostly we should hide inner header for preventing other lib using it, so flags like -iquote or -I is necessary in some rule like [objc_library.copts](https://docs.bazel.build/versions/master/be/objective-c.html#objc_library.copts)

So I create a patch for seperating the copts and move the search path part into `HEADER_SEARCH_PATHS` #56

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
