### ISSUE TITLE
Fail generate Xcode project with ios_unit_test or ios_ui_test rules

### ISSUE THREAD

**Issue by xinzhengzhang** [bazelbuild/tulsi#60]
My environment:
bazel: 0.17.2
rules_apple: 0.7.0
tulsi: master (https://github.com/bazelbuild/tulsi/commit/dcd32cf7fd7fe036920f65707e9629bb91e00b30)

Generate fail when ios_unit_test or ios_ui_test involved (Fine with ios_application,objc_library....)

Message log:
ERROR: /opt/iOS/loktar/bili-universal/Test/BUILD:10:1: in @tulsi//tulsi:tulsi_aspects.bzl%tulsi_sources_aspect aspect on apple_ui_test rule //bili-universal/Test:main_test: Traceback (most recent call last):
	File "/opt/iOS/loktar/bili-universal/Test/BUILD", line 10
		@tulsi//tulsi:tulsi_aspects.bzl%tulsi_sources_aspect(...)
	File "/private/tmp/loktar-bazel/external/tulsi/tulsi/tulsi_aspects.bzl", line 768, in _tulsi_sources_aspect
		provider.deps
'AppleTestInfo' object has no attribute 'deps'
Available attributes: includes, module_maps, non_arc_sources, sources, swift_modules
ERROR: Analysis of aspect '@tulsi//tulsi:tulsi_aspects.bzl%tulsi_sources_aspect of //bili-universal/Test:main_test' failed; build aborted: Analysis of target '//bili-universal/Test:main_test' failed; build aborted
General failure: Bazel aspects could not be built.

![image](https://user-images.githubusercontent.com/1487445/46143330-311d1680-c28c-11e8-92c4-34aa591d17a1.png)

**Comment by DavidGoldman** [comment]
Apologies, Tulsi currently depends on the HEAD version of `rules_apple` which may or may not be compatible with the latest Bazel release, I'll try to fix this up.

**Comment by DavidGoldman** [comment]
[`rules_apple 0.8.0`](https://github.com/bazelbuild/rules_apple/releases/tag/0.8.0) should fix this issue, can you confirm?

**Comment by xinzhengzhang** [comment]
Thanks for the fix. 
It works fine now.
