### ISSUE TITLE
Tulsi's Project config wizard is intermittently super-slow in Source targets creation step 

### ISSUE THREAD

**Issue by ravimandala** [bazelbuild/tulsi#61]
While editing or creating `Configs` in Tulsi GUI app, the last step where the Source targets are created is often super slow right before it loads the list of possible source targets. The spinner sometimes keeps spinning like... forever. Is this a known issue?

Here is what it is doing in the background...

> Running <abc_xyz>/bazel/bazel-bin/src/bazel --max_idle_secs=60 query '--override_repository=tulsi=<home_dir>/Library/Application Support/Tulsi/0.4.215728096.20181004/Bazel' --announce_rc --noimplicit_deps --order_output=no --noshow_loading_progress --noshow_progress buildfiles(deps(//:Albahaca)) --keep_going --output xml

Bazel version: _(source built from)_ **release-0.19.0**
Tulsi version: **0.4.215728096.20181004**

**Comment by DavidGoldman** [comment]
Unfortunately creating a Tulsi config is roughly equivalent to generating a project in terms of Bazel invocations - we invoke Bazel `query` and `build --aspects=...` just like we do when generating the `xcodeproj`.

This can be slow, especially if Bazel has to start up a new server. In fact, if you already have a Bazel command running, Tulsi's commands will wait for your Bazel command to finish. How long does it take for your project?

**Comment by ravimandala** [comment]
I have seen this particular step sometimes take 2-3 minutes with a spinner while retrieving a possible list of Source Targets, in a medium-sized project (3 BUILD files and ~45 dependencies).

**Comment by steeve** [comment]
I am having this problem on the latest tulsi master as of today.

Basically right after selecting the bazel binary, it spins without doing anything, basically for several minutes.

I'm doing it on a sample project: https://github.com/ffreling/bazel-ide-test

**Comment by dierksen** [comment]
@steeve You might be running into a different issue. I noticed a deadlock in the Tulsi UI that was introduced in the latest push. We'll get that fix pushed out today.

**Comment by keith** [comment]
Feel free to reopen if this is still an issue
