### ISSUE TITLE
Latest Tulsi doesn't build with Xcode 10

### ISSUE THREAD

**Issue by ravimandala** [bazelbuild/tulsi#62]
Tulsi was updated in this [recent commit](https://github.com/bazelbuild/tulsi/tree/50d0364eb1983dbf7a93eda764352fdb2f80c47f) to build with Bazel, but it has 2 issues.

1. It doesn't build with Xcode 10 like the previous version ([0.4.216764214.20181011](https://github.com/bazelbuild/tulsi/commit/57ce2f8f0522b38b98775755373b17b7d1f2b14e)) used to. 
1. The [README.md](https://github.com/bazelbuild/tulsi/blob/50d0364eb1983dbf7a93eda764352fdb2f80c47f/README.md) still suggests to build it using Xcode project -- which is gone.

Am I missing something? If it's still a work-in-progress, I can help.
@reinhillmann @dierksen @DavidGoldman

**Comment by dierksen** [comment]
Without modifications, I didn't think Tulsi was ever buildable with Xcode 10. There was a breaking change in Xcode 10 (which, funnily enough _isn't the same in OSS Swift..._) that changed `RunLoopMode` to `RunLoop.Mode`, which is a fairly trivial change, but we still need to support Xcode 9.x a bit longer. Are you seeing any other errors besides this one?

I'll update the README.md to explain this Xcode version limitation and how to build using Bazel.

**Comment by keith** [comment]
This is definitely possible if we wanted to support both. For that specific case you could fix it like this:

```swift
#if swift(>=4.2)
      let mode = RunLoop.Mode.default
#else
      let mode = RunLoopMode.defaultRunLoopMode
#endif

      // Add a dummy port to prevent the runloop from returning immediately.
      runLoop.add(NSMachPort(), forMode: mode)

      while !thread.isCancelled {
        runLoop.run(mode: mode, before: Date.distantFuture)
      }
```

There are quite a few uses of other AppKit APIs that changed between these versions though, so we'd have to do this conditional in a lot of places.

**Comment by DavidGoldman** [comment]
Last I looked into updating for Xcode 10 (Swift 4.2) we had about 13 files that needed minor changes (quite a few for `#if`s); as an alternative I think forcing Swift 4 instead of Swift 4.2 should work?

**Comment by keith** [comment]
Yep, using Xcode 10 this works for me to build tulsi:

```
bazel build //... --apple_platform_type=macos --swiftcopt=-swift-version --swiftcopt=4
```

builds for me.

I still get this error at the end, but I haven't built tulsi before so that could be unrelated:

```
ERROR: /Users/ksmiley/dev/tulsi/BUILD:85:1: error executing shell command: '/bin/bash -c unzip -oq bazel-out/darwin-fastbuild/bin/tulsi.zip -d bazel-out/darwin-fastbuild/genfiles/dmg_root && ln -s /Applications bazel-out/darwin-fastbuild/genfiles/dmg_root/Applications && m...' failed (Exit 1)
hdiutil: create failed - Operation not permitted
could not access /Volumes/Tulsi - Operation not permitted
```

**Comment by vahidk** [comment]
I think you can just compile as keith suggested and unzip bazel-bin/tulsi.zip and copy to Application folder. The above error happens in tulsi_dmg which is not really necessary.
