### ISSUE TITLE
Error when compiling: Use of undeclared type 'Process'

### ISSUE THREAD

**Issue by joprice** [bazelbuild/tulsi#64]
After cloning from master and running `bazel build ...` I get the following error:

```
src/TulsiGenerator/BazelAspectInfoExtractor.swift:43:42: error: use of undeclared type 'Process'
  private typealias CompletionHandler = (Process, String) -> Void
```
```
bazel version
Build label: 0.18.0-homebrew
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Oct 16 15:57:40 2018 (1539705460)
Build timestamp: 1539705460
Build timestamp as int: 1539705460
```

ios version 10.13.3

**Comment by dierksen** [comment]
If you're trying to build `...`, you probably need to specify `--cpu=darwin_x86_64` and `--apple_platform_type=macos`. Otherwise, I think the `swift_library` targets in lower-level directories will assume they're being built for iOS, which doesn't have `Process`.

**Comment by joprice** [comment]
Ok I see that now in `.travis.yml`. Can that be added to a checked-in bazelrc instead?
