### ISSUE TITLE
Tulsi IDE doesn't accept multiple environment variables

### ISSUE THREAD

**Issue by ravimandala** [bazelbuild/tulsi#66]
Tulsi IDE has a configuration to add environment variables but it seems to be a single line configuration. Adding a `\n` doesn't work as it is encoded with an extra `\`. One workaround to add multiple environment variables is to manually edit `Configs/<project-name>.tulsigen` and/or `project.tulsiconf` and add a `\n` to separate multiple environment variables. Am I missing something or is there a better way to do this?

\cc @DavidGoldman @reinhillmann @dierksen

**Comment by dierksen** [comment]
Yeah, that's a bug for now. Some (if not all) of the string options should be multi-line, but they're currently all single line. Until this is fixed, manually editing the config files as you mentioned is the simplest way to handle this.
