### ISSUE TITLE
Tulsi releases

### ISSUE THREAD

**Issue by ob** [bazelbuild/tulsi#69]
Are there any releases of Tulsi planned?

**Comment by ravimandala** [comment]
+1

@dierksen @DavidGoldman @reinhillmann

**Comment by nglevin** [comment]
Bystander and former Tulsi contributor.

Could you provide more context? Each of the pushes to Github should come with a version bump. That seems release-like to me!

I'm not sure what you mean by "release", if that's not the release channel you're referring to.

**Comment by ob** [comment]
I was talking about populating the [releases page](https://github.com/bazelbuild/tulsi/releases) in GitHub with binary releases.

**Comment by keith** [comment]
https://github.com/bazelbuild/tulsi/issues/21
