### ISSUE TITLE
Build errors in Xcode 8.2.1

### ISSUE THREAD

**Issue by robbiexperiel** [bazelbuild/tulsi#7]
I just cloned the repository and ran into 2 build errors when trying to build it using Xcode 8.2.1:
```
/Users/robbie/tulsi/src/TulsiGenerator/BazelLocator.swift:27:12: 'NSUserDefaults' has been renamed to 'UserDefaults'
/Users/robbie/tulsi/src/TulsiGenerator/TulsiProject.swift:108:62: Missing argument label 'workspaceRoot:' in call
```

**Comment by kelvinchan-google** [comment]
Good catch Robbie. We missed a few files. We're on it.

**Comment by jerrymarino** [comment]
@kelvinchan-google I submitted a patch to our fork and to Gerrit to fix this:

https://bazel-review.googlesource.com/#/c/9331/

https://github.com/pinterest/tulsi/pull/1

**Comment by kelvinchan-google** [comment]
We've got the change submitted internally to address this issue. Unfortunately our open-sourcing pipeline is having issues. We're looking into it now and hope to push a new version in the next day. Sorry for the inconvenience.

Our change is the following, if you'd like to mirror it into your branch:

In EventLogger.swift, lines 28 - 54 should be
  ```
deinit {
    if let observer = self.observer {
      NotificationCenter.default.removeObserver(observer)
    }
  }

  func startLogging() {
    observer = NotificationCenter.default.addObserver(forName: NSNotification.Name(rawValue: TulsiMessageNotification),
                                                      object: nil,
                                                      queue: nil) {
      [weak self] (notification: Notification) in
        guard let item = LogMessage(notification: notification),
              let verbose = self?.verbose, verbose || item.level != .Info else {
          return
        }

        let level: String = item.level.rawValue
        let details: String
        if let itemDetails = item.details {
          details = " \(itemDetails)"
        } else {
          details = ""
        }
        print("[\(level)] \(item.message)\(details)")
    }
  }
```

In BazelLocator.swift, lines 25 - 28 should be this
```
  static func findBazelForWorkspaceRoot(_ workspaceRoot: URL?) -> URL? {
    // TODO(abaire): Fall back to searching the user's path if no default exists.
    return UserDefaults.standard.url(forKey: BazelLocator.DefaultBazelURLKey)
  }
```

**Comment by robbiexperiel** [comment]
No problem, I cloned pinterest's fork and have been using a build from that in the meantime. Thanks for getting this fixed.

**Comment by kelvinchan-google** [comment]
Hi @robbiexperiel & @jerrymarino. We just pushed the new changes into the repo. That should fix the issues you were previously seeing. Let me know if you're still having issues.
