### ISSUE TITLE
Latest Tulsi doesn't expand resources embed in apple_resource_group

### ISSUE THREAD

**Issue by xinzhengzhang** [bazelbuild/tulsi#70]
The release notes in apple rules 0.10.0 said that 
`apple_resource_group will replace objc_library resource attributes`

https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-resources.md

I have replaced all my objc_library's `resources` attributes into `data` and wrap it using apple_resource_group and tulsi(0ad4f12) doesn't expand it into xcode project

**Comment by dierksen** [comment]
@sergiocampama FYI.

**Comment by xinzhengzhang** [comment]
ping

**Comment by sergiocampama** [comment]
This will take some time since almost everyone is out for the holidays

**Comment by xinzhengzhang** [comment]
Fixed in https://github.com/bazelbuild/tulsi/commit/278c2c65f104f87734ae2fa856cf861a9ff7630d

**Comment by dierksen** [comment]
I'm working on getting the `apple_resource_group` to propagate its resources up to its consumers, but anything that's in `resources` should be able to attach to `data` directly without the `apple_resource_group` wrapper IIUC. It's `structured_resources` where this is really necessary, but either way, will hopefully be resolved soon-ish.
