### ISSUE TITLE
ERROR when runing ./build_and_run.sh

### ISSUE THREAD

**Issue by czy2014hust** [bazelbuild/tulsi#73]
When runing ./build_and_run.sh, I get this ERROR: 
ERROR: tulsi/BUILD:61:1: TreeArtifact tulsi-intermediates/swiftlibs was not created
ERROR: tulsi/BUILD:61:1: not all outputs were created or valid
Bazel version is [Build label: 0.18.1]

**Comment by dierksen** [comment]
Can you use a newer version of Bazel? It's currently being tested with 0.21.0.

**Comment by ravimandala** [comment]
I agree. We use Tulsi with Bazel `0.20.0` and `./build_and_run.sh` works fine.

**Comment by czy2014hust** [comment]
Yes, build successfully with Bazel 0.21.0. Thanks!
