### ISSUE TITLE
Tulsi doesn't expand location templates currently supported by Bazel

### ISSUE THREAD

**Issue by ravimandala** [bazelbuild/tulsi#74]
Our Tulsi generated Xcode project has indexing and auto-complete issues. We figured that it is due to the **location template** that we use which is currently [supported by Bazel](https://github.com/bazelbuild/bazel/blob/1f332e0c33ba98e82a5ba32c4e7c298a4ac99eff/src/main/java/com/google/devtools/build/lib/skylarkbuildapi/SkylarkRuleContextApi.java#L715-L747) but not recognized/supported by Tulsi. This leads to different issues in Tulsi generated Xcode project like...

1. Inability to jump to the definition on certain symbols.
2. Not able to see proper method prototypes in auto-complete pop-up and finding `<<error type>>` instead.
3. Unable to build `_idx_*` targets which I assume means Xcode fails to index the most basic things.

However, if location template is expanded using `ctx.expand_location()` in `tulsi_aspects.bzl` (along with a minor patch in Bazel - to skip some validations) the indexing issue and `<<error type>>` in auto-complete pop-up get resolved.

So, I have a few questions...
1. Is this a known issue? If yes, is someone working on this? (I want to collaborate instead of duplicating the effort).
2. Does expanding location in `tulsi_aspects.bzl` sound like an appropriate fix here? 

Any other thoughts or questions or concerns?

\cc @DavidGoldman @reinhillmann @dierksen

**Comment by dierksen** [comment]
1. Not a known issue AFAIK.
2. Expanding location in the aspect is probably a reasonable way to handle that.

**Comment by ob** [comment]
I tried using `ctx.expand_location()` from an aspect but got hit with https://github.com/bazelbuild/bazel/issues/7083

**Comment by DavidGoldman** [comment]
Any idea what `ctx.expand_location()` is doing that improves indexing and auto-completion? Could Tulsi be modified to expand the location instead?

**Comment by ob** [comment]
In our case, we have some `copts` in the `objc_library()` rules that include calls to `$(location)`. Specifically, `-I$(location headermap)` which the rules expand to the location of a generated header map. Without explicitly expanding calling `ctx.expand_location()` in the Tulsi aspect, the Xcode generated project ends up with `HEADER_SEARCH_PATHS` set to something like `"-I$(location", "headermap)"` because the code is just splitting on space. This trips up Xcode's indexing.

**Comment by ravimandala** [comment]
@DavidGoldman, we have a PR, that's coming right up, to expand location using `ctx.expand_location()` in `tulsi_aspects.bzl` so that Xcode sees expanded header map paths instead of split up opts/attrs.

**Comment by dierksen** [comment]
Can you provide an example that we could add for an integration test?

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
