### ISSUE TITLE
Tulsi on OSX 10.12 with XCode 9.2

### ISSUE THREAD

**Issue by tmarkovich** [bazelbuild/tulsi#80]
I'd love to use Tulsi but I'm currently on osx 10.12.6 with xcode 9.2. What's the commit that I should check out to build?

**Comment by dierksen** [comment]
dcd32cf7fd7fe036920f65707e9629bb91e00b30 was the last one where Xcode 9.2 was explicitly supported, although it might still work for some things.

macOS 10.12 is the bigger issue. 34232fba2b79c398a24a0d83d4d607c82f14e16b is the commit where we started requiring 10.13 for `sortedKeys` on JSON dictionaries. Anything before that might still work with Xcode 9.2, but no guarantees.

**Comment by tmarkovich** [comment]
thanks!!
