### ISSUE TITLE
Generated Xcode project reports incorrect errors for dependencies

### ISSUE THREAD

**Issue by blairmatte** [bazelbuild/tulsi#87]
Minimal sample project to reproduce the issue: https://github.com/blairmatte/test_tulsi/tree/master

The project has one c++ dependency defined in `WORKSPACE` as a `new_git_repository`. The repo includes a `.tulsiproj` with one config called `main` that runs a `cc_binary` target. The project builds and runs successfully both from the command line and from Xcode, but Xcode reports errors for missing headers and types from the dependency.

<img width="1087" alt="Screen Shot 2019-04-25 at 2 04 40 PM" src="https://user-images.githubusercontent.com/48448052/56760199-b4421480-6768-11e9-8331-0e848fc2a936.png">

Xcode is also unable to perform autocompletion or report syntax errors for types from dependencies.

macOS version: 10.13.6
Xcode version: 10.1
Bazel version: 0.23.2
Tulsi version: 0.4.244069189.20190417

**Comment by Tyler-Keith-Thompson** [comment]
This also happens with `new_git_repository` and a swift library. Xcode falsely reports issues despite builds succeeding. Additionally, it can't lookup symbols or references. Nor can it syntax highlight correctly.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
