### ISSUE TITLE
Docs: .tulsigen file syntax is missing

### ISSUE THREAD

**Issue by baxissimo** [bazelbuild/tulsi#89]
If you search for a tag that works in the tulsigen files like "additionalFilePaths" you get no hits on any documentation.  Just source files that generally don't explain the syntax you can use for that tag.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
