### ISSUE TITLE
Tulsi cannot generate Xcodeproj that includes packages from local_repositories

### ISSUE THREAD

**Issue by adamhowardprice** [bazelbuild/tulsi#9]
See [repro project](https://github.com/adamhowardprice/bazel-repro-project)

**Comment by steren** [comment]
Thanks for the great repro steps @adamhowardprice.

Looping @dmishe and @kelvinchan-google for visibility.
Could you provide guidance? Is it a bug or a configuration problem?

**Comment by dmishe** [comment]
Sorry for the silence. We know that the problem is in Tulsi's inability to handle more than 1 workspace, which results in an incorrect blaze command issued. Ideally, we will add a way to pick a workspace each time you pick a BUILD file, this will require some major UI changes.

**Comment by dmishe** [comment]
Adam, what if you create two Tulsi projects (and therefore two Xcode projects) for different repos as a quick workaround? Would that work for you? Bazel would still build everything, as it knows about cross-repo references, and Tulsi won't complain.

**Comment by dflems** [comment]
https://github.com/dflems/bazel-repro/tree/master/tulsi-local-repo

**Comment by dmaclach** [comment]
Filed a bug with bazel directly (https://github.com/bazelbuild/bazel/issues/3970) that gets Tulsi out of the picture and shows that the path is being returned to Tulsi incorrectly (Tulsi is just parroting that path out to the Xcode project it writes out)

**Comment by dmaclach** [comment]
According to bazel folks, the path being returned is relative to exec root and needs to be resolved appropriately on Tulsi side. Looking into this.

**Comment by DavidGoldman** [comment]
@dflems Have you tried building the project through Xcode and re-opening the project? #20 seems to have made it so you need to build it once for the symlink to be set.

**Comment by dmaclach** [comment]
We think this is working (at least with the sample project that dlems sent us). Can you please give it a shot?

**Comment by dmaclach** [comment]
@dflems @adamhowardprice Can you let me know what isn't working for you? @DavidGoldman told me that he thought it was working, and when I tested it this AM it seemed to be functioning.
