### ISSUE TITLE
Support wildcards for "additionalFilePaths"

### ISSUE THREAD

**Issue by baxissimo** [bazelbuild/tulsi#90]
There are only some kinds of source files that tulsi knows about. For instance it doesn't include BUILD files or .metal files normally.  Even though those are both things you would probably like to edit from the comfort of your familar Xcode editor.

The additionalFilePaths tag will let you include them one-by-one. But it would be a lot easier if you could just specify a wildcard like `"src/**/BUILD"` or `"src/**/*.metal"`.

Maybe this already works? I'm not sure because the only documentation for this feature seems to be the one line comment in TulsiGeneratorConfig.swift:
```
    /// Additional file paths to add to the Xcode project (e.g., BUILD file paths).
```

**Comment by DavidGoldman** [comment]
Don't have any plans to add support for this right now, most relevant files are automatically discovered through the aspect.

re: BUILD files, have you seen the `IncludeBuildSources` option? That should add all build files used into the project.

**Comment by baxissimo** [comment]
Thank, didn't know about `IncludeBuildSources`.

If not a user wildcard type option, the project generation should still include *.metal files normally.  That are a kind of Apple source file, and e.g. syntax errors in a .metal file are highlighted by Xcode.

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
