### ISSUE TITLE
Breaks with incompatible_depset_is_not_iterable

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/tulsi#95]
Tulsi is broken with Bazel 0.27: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1017#f1db9866-91a4-4ed5-823b-47679896dbab

The error has already been fixed in Swift (https://github.com/bazelbuild/rules_swift/commit/19129584e2d9351eb7245afd37693976f4c50198), so I think you just need to update your dependencies.

Let me know if you need help (I don't have a Mac, which makes harder to contribute)

**Comment by DavidGoldman** [comment]
I believe rules_apple and rules_swift just cut new releases, so I'll try updating our dependencies and see if that fixes it.

**Comment by DavidGoldman** [comment]
I believe this should be fixed as of 1cb0527be12

**Comment by laurentlb** [comment]
Indeed! I've rerun the tests a few minutes ago and it was green.

Thanks a lot!
