### ISSUE TITLE
Code completion/highlights not working in Swift

### ISSUE THREAD

**Issue by rebello95** [bazelbuild/tulsi#96]
**Overview**

When using Tulsi to generate an Xcode project with a `swift_library` target and corresponding `ios_unit_test`, all the source code appears correctly in the project, but code completion and jumping to definitions does not work. 

Building the project and running the tests works properly.

When generating with an [additional `objc_library` target](https://github.com/lyft/envoy-mobile/blob/6db2c85b0e00583c10d2d2ff6d2a8f14d3ac143d/library/objective-c/BUILD#L11), code completion and definition jumping in the Objective-C files works correctly, but Swift still does not.

**Reproducing**

This is currently 100% reproducible using [this sha](https://github.com/lyft/envoy-mobile/pull/256/commits/56712c3ced487ef2329e67698c8e039f1c7e373b) from [this Envoy Mobile PR](https://github.com/lyft/envoy-mobile/pull/256/files) after generating a Tulsi project and opening it.

**Screenshots**

For example, command-clicking on this type in Xcode will yield a `?` modal in Xcode, and the properties are not available in code completion:

<img width="1552" alt="Screen Shot 2019-07-12 at 3 23 44 PM" src="https://user-images.githubusercontent.com/2643476/61161537-0fa6b780-a4b9-11e9-95e2-fbf504c2d5d1.png">

<img width="1552" alt="Screen Shot 2019-07-12 at 3 27 11 PM" src="https://user-images.githubusercontent.com/2643476/61161640-98bdee80-a4b9-11e9-96ba-ccf7f24e5995.png">

**Comment by thii** [comment]
There's a workaround to make code completion and highlighting work: build the indexing target once (the build doesn't need to be success).

**Comment by thii** [comment]
I seems to be because of custom Swift compiler flags, because Tulsi doesn't expand the Make variables correctly. You can remove all flags in **Other Swift Flags** from the generated project to make the code completion/highlights work. But it won't compile from Xcode anymore of course 🙃.

**Comment by rebello95** [comment]
Removing the `Other Swift Flags` from the Envoy Mobile project above seems to have the same issue with completion/highlights. Did this work successfully for you?

**Comment by thii** [comment]
Yes, it worked for me.

Did you remove it from the indexing target? (the framework target starts with `_idx_`)

<img width="961" alt="Screen Shot 2019-12-31 at 17 20 32" src="https://user-images.githubusercontent.com/4506500/71614994-27523380-2bf2-11ea-836a-983695680c1b.png">
<img width="1333" alt="Screen Shot 2019-12-26 at 23 20 45" src="https://user-images.githubusercontent.com/4506500/71614995-2a4d2400-2bf2-11ea-9e89-77aaa39adb6d.png">

**Comment by rebello95** [comment]
> Did you remove it from the indexing target? (the framework target starts with _idx_)

Aha, I had removed the flags from the wrong targets. Doing what you suggested above seems to mitigate the issue, which works if you then build from the command line 👍

**Comment by thii** [comment]
I think it would still works if you build from Xcode since you aren't supposed to build the indexing target (though I'm not sure how it would affect the indexing data).

**Comment by keith** [comment]
Thanks for submitting this issue but this tool is being deprecated. Please checkout [rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj) for a more complete and maintained Xcode integration.
